"""End-to-end rendering tests — generate() → CodegenResult.files.

Pins: the public API (LayerGraph or JSON input), output_dir tree
writing, the SPLIT golden's full 33-file tree (byte-stable), golden
spot-checks for methods/enums/concepts, and the as-built .cpp path.
"""

from __future__ import annotations

import json
from pathlib import Path

from codegraph.codegen import CodegenResult, generate, generate_from_layer_graph
from codegraph.graph import LayerGraph

GOLDEN_DIR = Path(__file__).resolve().parent / "golden"

FULL_DECL = json.loads((GOLDEN_DIR / "design_layergraph_full_decl.json").read_text())
SPLIT = json.loads((GOLDEN_DIR / "design_layergraph.json").read_text())


class TestGenerate:
    def test_generate_from_json_list(self):
        result = generate(FULL_DECL)
        assert isinstance(result, CodegenResult)
        assert "include/cpp_sqlite/Migration.hpp" in result.files

    def test_generate_from_layer_graph(self):
        graph = LayerGraph.deserialize(FULL_DECL)
        result = generate_from_layer_graph(graph)
        assert "include/cpp_sqlite/Migration.hpp" in result.files

    def test_result_summary(self):
        result = generate(FULL_DECL)
        assert "7 file(s)" in result.summarize()
        assert "skipped:" in result.summarize()

    def test_output_dir_writes_tree(self, tmp_path: Path):
        result = generate(FULL_DECL, output_dir=tmp_path)
        dest = tmp_path / "include/cpp_sqlite/MigrationManager.hpp"
        assert dest.exists()
        assert dest.read_text() == result.files["include/cpp_sqlite/MigrationManager.hpp"]

    def test_language_alias_normalized(self):
        # normalize_language('C++') → 'cpp'; builtin pack still loads.
        result = generate(FULL_DECL, language="C++")
        assert len(result.files) == 7


class TestSplitGoldenRender:
    def test_full_tree_renders(self):
        result = generate(SPLIT)
        assert len(result.files) == 33
        assert all(text.endswith("\n") for text in result.files.values())

    def test_rendering_is_deterministic(self):
        a = generate(SPLIT)
        b = generate(SPLIT)
        assert a.files == b.files

    def test_concept_initializer_verbatim(self):
        """Concept initializer renders with the namespace qualification
        stripped (qualified concept definitions confuse doxygen and would
        never round-trip)."""
        result = generate(SPLIT)
        text = result.files["include/cpp_sqlite/CopyableTransferObject.hpp"]
        assert (
            "template<typename T> concept CopyableTransferObject "
            "= TransferObject<T> && std::copyable<T>" in text
        )
        assert "concept cpp_sqlite::CopyableTransferObject" not in text

    def test_guard_and_provenance(self):
        result = generate(SPLIT)
        text = result.files["include/cpp_sqlite/MigrationManager.hpp"]
        assert "#ifndef INCLUDE_CPP_SQLITE_MIGRATIONMANAGER_HPP" in text
        # R7 markers are opt-in (default off — they break byte-fidelity
        # with hand-written source; verify() never reads them).
        assert "// @codegraph uid:" not in text
        assert "// GENERATED by codegraph-codegen" in text

    def test_provenance_markers_opt_in(self):
        result = generate(SPLIT, emit_markers=True)
        text = result.files["include/cpp_sqlite/MigrationManager.hpp"]
        assert "// @codegraph uid:" in text

    def test_forward_decls_rendered_before_class(self):
        """DEPENDS_ON class targets forward-declared inside the namespace;
        std:: refs and nested dup structs (defined in this header) are not."""
        result = generate(SPLIT)
        text = result.files["include/cpp_sqlite/MigrationManager.hpp"]
        decl = text.index("class MigrationManager")
        for name in ("Database", "Migration", "SchemaVersion"):
            assert text.index(f"class {name};") < decl, f"missing forward decl {name}"
        # std:: is never synthesized as a file → never forward-declared
        assert "class std::" not in text
        assert "class vector;" not in text
        # the composed nested dup struct is defined in this header, not
        # forward-declared (D9)
        assert "struct MigrationResult;" not in text


class TestAsBuiltSource:
    def test_source_file_renders_definitions(self):
        """As-built .cpp: body-carrying members render out-of-line defns."""
        graph = LayerGraph.deserialize([
            {
                "type": "FileNode",
                "name": "DBDAOBase.cpp",
                "path": "cpp_sqlite/src/cpp_sqlite/DBDAOBase.cpp",
                "language": "C++",
                "source": "test",
                "tags": ["as-built"],
            },
            {
                "type": "ClassNode",
                "name": "DAOBase",
                "qualified_name": "cpp_sqlite::DAOBase",
                "kind": "class",
                "file_path": "cpp_sqlite/src/cpp_sqlite/DBDAOBase.cpp",
                "source": "test",
                "tags": ["as-built"],
                "composes": [
                    {
                        "type": "MethodNode",
                        "name": "isInitialized",
                        "qualified_name": "cpp_sqlite::DAOBase::isInitialized",
                        "kind": "method",
                        "type_signature": "bool",
                        "argsstring": "() const override",
                        "definition": "bool cpp_sqlite::DAOBase::isInitialized",
                        "body_start": 5,
                        "body_end": 8,
                        "source": "test",
                        "tags": ["as-built"],
                    },
                ],
            },
        ])
        result = generate_from_layer_graph(graph)
        assert set(result.files) == {"cpp_sqlite/src/cpp_sqlite/DBDAOBase.cpp"}
        text = result.files["cpp_sqlite/src/cpp_sqlite/DBDAOBase.cpp"]
        assert "bool cpp_sqlite::DAOBase::isInitialized() const override" in text
        assert "TODO(codegen): implementation body" in text
