"""PlantUML visualisation and round-trip fidelity tests for
the cpp-sqlite as-built graph.

Verifies that the PlantUML exporter produces valid class-diagram
syntax with expected elements and relationships, and that a full
round-trip (LayerGraph → PlantUML → LayerGraph → PlantUML) produces
identical output.
"""

from __future__ import annotations

import pytest

from .artifacts import CODEGRAPH_OUTPUT as _CODEGRAPH_OUTPUT
from .artifacts import UNIT_TEST_DATA as _UNIT_TEST_DATA



def _stamp_imported_graph_keys(graph):
    """Stamp canonical keys on nodes produced by PlantUML import."""
    from urllib.parse import quote

    for entry in graph._all_entries():
        node = entry.node
        qname = getattr(node, "qualified_name", "") or getattr(node, "name", "")
        category = type(node).__name__.removesuffix("Node").lower()
        node.canonical_key = (
            "cg:v1:repository:cpp-sqlite%2Fcpp-sqlite:"
            f"{category}:qualified_name={quote(qname, safe='')}"
        )
    return graph


class TestPlantUMLExport:
    """Verify the PlantUML export contains expected elements and
    relationships for the cpp-sqlite as-built graph.

    The ``.puml`` file is generated by the session-scoped
    ``codegraph_graph`` fixture in conftest alongside JSON and HTML.
    """

    @pytest.fixture(scope="class")
    def puml_text(self, codegraph_graph):
        """Load the PlantUML text generated by the session fixture."""
        puml_path = _CODEGRAPH_OUTPUT / "cpp_sqlite_preservation_one_hop.puml"
        assert puml_path.exists(), f"PUML not found at {puml_path}"
        return puml_path.read_text(encoding="utf-8")

    @pytest.fixture(scope="class")
    def puml_lines(self, puml_text):
        """Split the PlantUML text into non-empty, non-comment lines."""
        return [
            L for L in puml_text.split("\n")
            if L.strip() and not L.strip().startswith("'")
            and not L.strip().startswith("@")
            and not L.strip().startswith("skinparam")
        ]

    # ------------------------------------------------------------------
    # Structure
    # ------------------------------------------------------------------

    def test_puml_has_startuml(self, puml_text):
        """The PlantUML output is wrapped in @startuml / @enduml."""
        assert "@startuml" in puml_text
        assert "@enduml" in puml_text

    def test_puml_has_namespace_package(self, puml_lines):
        """Top-level package declarations for key namespaces."""
        assert any("package" in L and "cpp_sqlite" in L for L in puml_lines)

    # ------------------------------------------------------------------
    # Element assertions
    # ------------------------------------------------------------------

    def test_puml_has_key_classes(self, puml_lines):
        """Core project classes appear as PlantUML elements."""
        for cls_name in (
            "Database",
            "Transaction",
            "TransactionError",
            "DataAccessObject",
            "ForeignKey",
        ):
            assert any(
                cls_name in L and ("class" in L or "interface" in L)
                for L in puml_lines
            ), f"Missing class element for {cls_name}"

    def test_puml_has_key_functions(self, puml_lines):
        """Free functions (non-member callables) appear as <<function>> stereotypes."""
        # The cpp-sqlite project has free functions like IsVector, IsForeignKey
        assert any(
            "<<function>>" in L for L in puml_lines
        ), "Expected at least one <<function>> stereotype"

    def test_puml_has_concepts(self, puml_lines):
        """C++20 concept nodes appear with <<concept>> stereotype."""
        assert any(
            "<<concept>>" in L for L in puml_lines
        ), "Expected at least one <<concept>> stereotype"

    def test_puml_has_boost_spdlog_packages(self, puml_lines):
        """External libraries (boost, spdlog) have their own packages."""
        packages = [L for L in puml_lines if "package" in L]
        package_names = " ".join(packages)
        assert "boost" in package_names, "Missing boost package"
        assert "spdlog" in package_names, "Missing spdlog package"

    def test_puml_has_member_lines(self, puml_lines):
        """Compounds contain member lines (methods/attributes)."""
        # Member lines start with visibility prefix after indentation,
        # e.g. '  +select(PreparedSQLStmt &stmt) : void'
        member_lines = [
            L for L in puml_lines
            if L.strip() and L.strip()[0] in "+-#"
        ]
        assert len(member_lines) > 5, (
            f"Expected >5 member lines, got {len(member_lines)}"
        )

    # ------------------------------------------------------------------
    # Relationship assertions
    # ------------------------------------------------------------------

    def test_puml_has_depends_on_arrows(self, puml_lines):
        """DEPENDS_ON edges appear as labelled dotted arrows."""
        deps = [L for L in puml_lines if "depends_on" in L.lower()]
        assert len(deps) > 0, "Expected DEPENDS_ON arrows"

    def test_puml_has_invokes_arrows(self, puml_lines):
        """INVOKES edges appear as labelled arrows."""
        invokes = [L for L in puml_lines if "invokes" in L.lower()]
        assert len(invokes) > 0, "Expected INVOKES arrows"

    def test_no_member_aliases_as_arrow_targets(self, puml_text):
        """No arrow target should be a member alias (e.g.
        ``cpp_sqlite__Database__getDAO``).  Members are rendered inline
        inside their parent class body and are never standalone
        PlantUML elements — targeting a member alias produces an
        unresolved arrow pointing to nothing.

        The check is structural: every arrow target must be an alias
        that was actually declared as a standalone element (class,
        interface, enum, union, package, or note).  (A previous
        "lowercase-last-segment" heuristic produced false positives
        for boost's lowercase-named classes like
        ``boost::checked_deleters::checked_array_deleter``.)"""
        import re
        declared = set()
        for line in puml_text.splitlines():
            m = re.match(
                r'(?:class|interface|enum|union|package|note)\s+"[^"]*"\s+as\s+(\S+)',
                line.strip(),
            )
            if m:
                declared.add(m.group(1))
        arrow_pattern = re.compile(
            r'(\S+)\s+(<\|--|\.\.\|>|\.\.>|-->|o--|\*--)\s+(\S+)\s+:'
        )
        for line in puml_text.splitlines():
            m = arrow_pattern.search(line)
            if m and m.group(3) not in declared:
                raise AssertionError(
                    f"Arrow target is not a declared element "
                    f"(member alias?): {line.strip()!r}"
                )

    def test_puml_has_arrow_to_sqlite3(self, puml_lines):
        """Select methods invoke sqlite3 C API functions."""
        sqlite_lines = [L for L in puml_lines if "sqlite3" in L and "..>" in L]
        assert len(sqlite_lines) > 0, (
            f"Expected arrows to sqlite3, none found in {len(puml_lines)} lines"
        )

    def test_puml_has_inheritance(self, puml_lines):
        """INHERITS_FROM edges use <|-- arrows."""
        inherit_lines = [L for L in puml_lines if "<|--" in L]
        assert len(inherit_lines) > 0, "Expected at least one inheritance arrow"

    # ------------------------------------------------------------------
    # PNG rendering
    # ------------------------------------------------------------------

    def test_puml_svg_generated(self, codegraph_graph):
        """The PlantUML file was rendered to a *valid* SVG.  SVG is
        preferred for large diagrams because it has no 4096px clipping
        limit that affects PNG output.

        Validation goes beyond "file exists": PlantUML exits 0 even on
        syntax errors and emits an error-page SVG (the source echoed as
        text plus a red ``Syntax Error?`` footer) instead of failing, so
        ``<svg>`` tags + size checks all pass on a broken diagram.
        ``validate_plantuml_svg`` rejects error pages, so this test
        fails loudly when the exporter produces PlantUML that cannot
        render."""
        from codegraph.export.plantuml import validate_plantuml_svg

        svg_path = _CODEGRAPH_OUTPUT / "cpp_sqlite_preservation_one_hop.svg"
        assert svg_path.exists(), (
            f"SVG not generated at {svg_path} — plantuml CLI may be missing"
        )
        # SVG must be well-formed XML and NOT a PlantUML error page.
        svg_text = svg_path.read_text(encoding="utf-8")
        problems = validate_plantuml_svg(svg_text)
        assert not problems, (
            "SVG is not a valid rendered diagram:\n  "
            + "\n  ".join(problems)
        )
        print(f"\n  SVG: {svg_path.stat().st_size:,} bytes (validated)")


class TestPlantUMLRoundTrip:
    """Verify round-trip fidelity:

    LayerGraph (Neo4j/JSON) → PlantUML → LayerGraph → PlantUML

    The PlantUML importer is a generic PlantUML parser — it derives
    qualified names from nesting, not from alias text.  The exporter
    emits ``std::runtime_error`` as a top-level ``class
    "runtime_error" as std__runtime_error`` without a ``std``
    package (because the as-built graph presents it as a root
    entry).  The importer therefore can't reconstruct the ``std::``
    namespace prefix, so exact byte-level round-trip fidelity is
    not achievable without restructuring the graph.

    We verify instead that the round-tripped graph has the same
    key classes, relationships, and overall structure — and that
    a second round-trip produces identical output (the importer
    is idempotent for graphs that don't mix namespace-level and
    top-level class aliases).
    """

    @pytest.fixture(scope="class")
    def puml_text(self, codegraph_graph):
        """Load the original PlantUML text from the session fixture."""
        puml_path = _CODEGRAPH_OUTPUT / "cpp_sqlite_preservation_one_hop.puml"
        assert puml_path.exists(), f"PUML not found at {puml_path}"
        return puml_path.read_text(encoding="utf-8")

    @pytest.fixture(scope="class")
    def roundtrip_puml(self, puml_text):
        """Import the PlantUML → LayerGraph → export back to PlantUML."""
        from codegraph.export.plantuml import import_plantuml, export_plantuml

        graph = _stamp_imported_graph_keys(
            import_plantuml(puml_text, tags=frozenset({"as-built"}))
        )
        return export_plantuml(graph, fields="all")

    # ------------------------------------------------------------------
    # Fidelity
    # ------------------------------------------------------------------

    def test_roundtrip_structure_stable(self, puml_text, roundtrip_puml):
        """The round-tripped PlantUML has the same @startuml/@enduml
        framing and non-zero content."""
        assert "@startuml" in roundtrip_puml
        assert "@enduml" in roundtrip_puml
        assert len(roundtrip_puml.strip()) > 100

    def test_roundtrip_idempotent_same_edge_count(self, roundtrip_puml):
        """A second round-trip produces output that can be
        successfully imported (no crash) and retains key relationships.

        Exact byte-identity is not expected because the PlantUML
        importer derives qualified names from nesting, while the
        exporter uses ``_sanitize_alias`` on the original qualified
        names.  Top-level ``class "runtime_error" as
        std__runtime_error`` becomes ``runtime_error`` (no namespace)
        on round-trip."""
        from codegraph.export.plantuml import import_plantuml, export_plantuml

        graph3 = _stamp_imported_graph_keys(
            import_plantuml(roundtrip_puml, tags=frozenset({"as-built"}))
        )
        puml3 = export_plantuml(graph3, fields="all")

        # Both should have the 4 INHERITS_FROM edges
        for puml in (roundtrip_puml, puml3):
            assert "inherits_from" in puml, (
                "Expected inherits_from edges in round-trip"
            )

        # Both should have relationship arrows
        assert "..>" in roundtrip_puml
        assert "..>" in puml3

        print(f"\n  Edges pass 2: {roundtrip_puml.count(chr(10))} lines")
        print(f"  Edges pass 3: {puml3.count(chr(10))} lines")

    def test_roundtrip_node_counts(self, codegraph_graph, roundtrip_puml):
        """The round-tripped graph has the same number of top-level entries."""
        _serialized, uid_map = codegraph_graph
        from codegraph.export.plantuml import import_plantuml
        graph = import_plantuml(roundtrip_puml, tags=frozenset({"as-built"}))

        # The round-tripped graph preserves the overall node count
        all_entries = list(graph._all_entries())
        # Allow small delta due to member-level differences in import
        assert len(all_entries) > 0, "Round-tripped graph should have entries"
        print(f"\n  Original nodes: {len(uid_map)}, round-trip nodes: {len(all_entries)}")

    def test_roundtrip_has_key_classes(self, roundtrip_puml):
        """Key classes survive the round-trip."""
        for cls_name in ("Database", "Transaction", "DataAccessObject"):
            assert cls_name in roundtrip_puml, (
                f"{cls_name} missing from round-tripped PlantUML"
            )

    def test_roundtrip_reenport_is_valid(self, roundtrip_puml):
        """Re-importing the re-exported PlantUML succeeds (no hard parse
        errors).  We use non-strict mode because the re-imported graph
        drops std types (they were top-level in the original but have
        no namespace in the round-tripped output)."""
        from codegraph.export.plantuml import import_plantuml
        graph = import_plantuml(roundtrip_puml, tags=frozenset({"as-built"}))
        assert len(graph.entries) > 0
        print(f"\n  Re-import entries: {len(graph.entries)}")


class TestCollapsedDependencyView:
    """Verify the ``view=GraphView.COLLAPSED`` PlantUML export
    collapses external dependencies (std, boost, spdlog, sqlite3)
    into simple package declarations with aggregated edges, and
    omits file nodes and file-reference edges.

    The collapsed ``.puml`` and ``.svg`` are generated by the
    session-scoped ``codegraph_graph`` fixture alongside the full
    PlantUML output.
    """

    @pytest.fixture(scope="class")
    def collapsed_puml(self, codegraph_graph):
        """Load the collapsed PlantUML text produced by the session fixture."""
        puml_path = _CODEGRAPH_OUTPUT / "cpp_sqlite_preservation_one_hop_collapsed.puml"
        assert puml_path.exists(), f"Collapsed PUML not found at {puml_path}"
        text = puml_path.read_text(encoding="utf-8")
        print(f"\n  Collapsed PUML: {len(text.splitlines())} lines")
        return text

    # ------------------------------------------------------------------
    # Package assertions
    # ------------------------------------------------------------------

    def test_has_external_packages(self, collapsed_puml):
        """External deps appear as simple ``package`` declarations."""
        for pkg in ("std", "boost", "spdlog", "sqlite3"):
            assert f'package "{pkg}" as {pkg}' in collapsed_puml, (
                f"Missing collapsed package: {pkg}"
            )

    def test_no_individual_std_types(self, collapsed_puml):
        """Individual std types (vector, optional, etc.) are NOT
        emitted as standalone elements — they are collapsed into the
        ``std`` package.  Template specialization aliases like
        ``IsVector__std__vector__...`` are fine."""
        import re
        # Check that no standalone class/edge declaration uses these
        # aliases.  Use word-boundary checks to avoid matching
        # substrings inside longer template aliases.
        collapsed_lines = set(collapsed_puml.splitlines())
        for extern in ("std__vector", "std__optional", "std__runtime_error",
                        "std__unique_ptr", "std__shared_ptr", "std__mutex"):
            # Check if any line has this as a standalone alias
            # (not part of a longer identifier)
            pattern = re.compile(
                r'(?:^|\b)' + re.escape(extern) + r'(?:\b|$)'
            )
            for line in collapsed_lines:
                if pattern.search(line):
                    # Exclude template aliases like IsVector__std__vector_...
                    if line.startswith("cpp_sqlite__") and ("<|" in line or "..>" in line):
                        continue  # template specialization, fine
                    if " as " + extern in line:
                        raise AssertionError(
                            f"Individual type {extern} appears as element: {line}"
                        )
                    # Also check if it's a standalone edge target
                    if "..> " + extern in line or "--> " + extern in line or "<|-- " + extern in line:
                        raise AssertionError(
                            f"Individual type {extern} appears as edge target: {line}"
                        )

    def test_no_individual_sqlite3_functions(self, collapsed_puml):
        """Individual sqlite3 functions are collapsed into the
        ``sqlite3`` package."""
        for func in ("sqlite3_step", "sqlite3_bind_int64",
                      "sqlite3_finalize", "sqlite3_prepare_v2"):
            assert func not in collapsed_puml, (
                f"Individual function {func} should be collapsed"
            )

    def test_no_member_aliases_as_arrow_targets(self, collapsed_puml):
        """No arrow target in the collapsed view should be a member
        alias (e.g. ``cpp_sqlite__Database__getDAO``).  Members are
        rendered inline and are never standalone elements.

        The check is structural: every arrow target must be an alias
        declared as a standalone element (class, interface, enum,
        union, package, or note) in the collapsed view."""
        import re
        declared = set()
        for line in collapsed_puml.splitlines():
            m = re.match(
                r'(?:class|interface|enum|union|package|note)\s+"[^"]*"\s+as\s+(\S+)',
                line.strip(),
            )
            if m:
                declared.add(m.group(1))
        arrow_pattern = re.compile(
            r'(\S+)\s+(<\|--|\.\.\|>|\.\.>|-->|o--|\*--)\s+(\S+)\s+:'
        )
        for line in collapsed_puml.splitlines():
            m = arrow_pattern.search(line)
            if m and m.group(3) not in declared:
                raise AssertionError(
                    f"Collapsed arrow target is not a declared element "
                    f"(member alias?): {line.strip()!r}"
                )

    # ------------------------------------------------------------------
    # Relationship assertions
    # ------------------------------------------------------------------

    def test_edges_redirect_to_packages(self, collapsed_puml):
        """Edges that targeted individual external types are now
        redirected to their package alias."""
        assert "cpp_sqlite__Database ..> std : depends_on" in collapsed_puml
        assert "cpp_sqlite__Database ..> sqlite3 : depends_on" in collapsed_puml
        assert "cpp_sqlite__Database ..> sqlite3 : invokes" in collapsed_puml
        assert "cpp_sqlite__TransactionError <|-- std : inherits_from" in collapsed_puml

    def test_no_depends_on_to_individual_types(self, collapsed_puml):
        """No ``depends_on`` arrows target individual external type
        aliases — they all go to package aliases."""
        import re
        deps = re.findall(
            r'^\.\.>\s+(\S+)\s+:\s+depends_on',
            collapsed_puml, re.MULTILINE,
        )
        # Heuristic: individual types have '__' in their alias (from ::)
        # e.g. std__vector, boost__unordered_map
        individual = [d for d in deps if "__" in d]
        # Project-internal types like cpp_sqlite__Database are fine
        individual_external = [d for d in individual
                               if not d.startswith("cpp_sqlite__")]
        assert len(individual_external) == 0, (
            f"External individual type targets found: {individual_external}"
        )

    def test_collapsed_view_smaller_than_full(self, collapsed_puml):
        """The collapsed view is significantly smaller than the
        full-detail PlantUML."""
        full_path = _CODEGRAPH_OUTPUT / "cpp_sqlite_preservation_one_hop.puml"
        full_puml = full_path.read_text(encoding="utf-8")

        collapsed_arrows = len([L for L in collapsed_puml.splitlines()
                                if "..>" in L or "-->" in L or "<|--" in L])
        full_arrows = len([L for L in full_puml.splitlines()
                           if "..>" in L or "-->" in L or "<|--" in L])
        assert collapsed_arrows < full_arrows, (
            f"Collapsed view ({collapsed_arrows} arrows) should be"
            f" smaller than full view ({full_arrows} arrows)"
        )
        print(f"\n  Full: {len(full_puml.splitlines())} lines, {full_arrows} arrows")
        print(f"  Collapsed: {len(collapsed_puml.splitlines())} lines, {collapsed_arrows} arrows")

    # ------------------------------------------------------------------
    # Fidelity: no information lost in the collapse
    # ------------------------------------------------------------------

    def test_collapse_preserves_all_external_edges(self, collapsed_puml):
        """Every edge in the full PlantUML that targets an external
        type (std::*, sqlite3_*, boost::*, spdlog::*, fmt::*, ...) has
        a corresponding edge in the collapsed view redirected to the
        package alias — for edges whose SOURCE is project code.

        Edges between two external types (e.g. boost→boost) are
        intentionally dropped by the collapse: both endpoints fold into
        the same package, so the edge would collapse to a self-loop
        (``boost ..> boost``) and represents no project dependency.
        """
        import re
        full_path = _CODEGRAPH_OUTPUT / "cpp_sqlite_preservation_one_hop.puml"
        full_puml = full_path.read_text(encoding="utf-8")

        def _parse(puml):
            edges = set()
            for L in puml.splitlines():
                m = re.match(
                    r'(\S+)\s+(<\|--|\.\.\|>|\.\.>|-->|o--|\*--)\s+(\S+)\s+:\s+(\S+)',
                    L,
                )
                if m:
                    edges.add((m.group(1), m.group(2), m.group(3), m.group(4)))
            return edges

        full_edges = _parse(full_puml)
        collapsed_edges = _parse(collapsed_puml)

        # Map external target aliases → package names
        def _to_package(alias):
            if alias == "sqlite3" or alias.startswith("sqlite3_"):
                return "sqlite3"
            if "__" in alias:
                prefix = alias.split("__")[0]
                if prefix in ("std", "boost", "spdlog",
                              "detail", "fmt", "mp_cond"):
                    return prefix
            if alias in ("detail", "fmt", "mp_cond"):
                return alias
            return None

        lost: list[tuple] = []
        for src, arrow, tgt, label in full_edges:
            pkg = _to_package(tgt)
            if pkg and _to_package(src) is None \
                    and (src, arrow, pkg, label) not in collapsed_edges:
                lost.append((src, arrow, tgt, label, pkg))

        assert len(lost) == 0, (
            f"{len(lost)} external edges lost in collapse:\n"
            + "\n".join(
                f"  {s} {a} {t} : {l} → expected {p}"
                for s, a, t, l, p in lost[:10]
            )
        )

    def test_collapse_no_spurious_edges(self, collapsed_puml):
        """Every edge in the collapsed view that targets an external
        package can be traced back to at least one edge in the full
        view.  No synthetic edges are invented."""
        import re
        full_path = _CODEGRAPH_OUTPUT / "cpp_sqlite_preservation_one_hop.puml"
        full_puml = full_path.read_text(encoding="utf-8")

        def _parse(puml):
            edges = set()
            for L in puml.splitlines():
                m = re.match(
                    r'(\S+)\s+(<\|--|\.\.\|>|\.\.>|-->|o--|\*--)\s+(\S+)\s+:\s+(\S+)',
                    L,
                )
                if m:
                    edges.add((m.group(1), m.group(2), m.group(3), m.group(4)))
            return edges

        full_edges = _parse(full_puml)
        collapsed_edges = _parse(collapsed_puml)

        pkg_targets = {"std", "sqlite3", "boost", "spdlog", "detail", "fmt", "mp_cond"}

        def _to_package(alias):
            if alias == "sqlite3" or alias.startswith("sqlite3_"):
                return "sqlite3"
            if "__" in alias:
                prefix = alias.split("__")[0]
                if prefix in ("std", "boost", "spdlog"):
                    return prefix
            if alias in ("detail", "fmt", "mp_cond"):
                return alias
            return None

        spurious: list[tuple] = []
        for src, arrow, tgt, label in collapsed_edges:
            if tgt not in pkg_targets:
                continue
            found = any(
                s == src and a == arrow and _to_package(t) == tgt and l == label
                for s, a, t, l in full_edges
            )
            if not found:
                spurious.append((src, arrow, tgt, label))

        assert len(spurious) == 0, (
            f"{len(spurious)} spurious edges in collapsed view:\n"
            + "\n".join(
                f"  {s} {a} {t} : {l}" for s, a, t, l in spurious[:10]
            )
        )

    # ------------------------------------------------------------------
    # File node assertions (COLLAPSED and PUBLIC_API both omit files)
    # ------------------------------------------------------------------

    def test_no_file_nodes(self, collapsed_puml):
        """File nodes (``note`` elements) are removed from the
        collapsed view."""
        import re
        note_lines = [
            L for L in collapsed_puml.splitlines()
            if re.match(r'^\s*note\s+"', L)
        ]
        assert len(note_lines) == 0, (
            f"Found {len(note_lines)} file note lines in collapsed view"
        )

    def test_no_includes_edges(self, collapsed_puml):
        """File-reference edges (``includes``) are removed from the
        collapsed view."""
        assert " : includes" not in collapsed_puml, (
            "Includes edges should not appear in collapsed view"
        )


class TestPublicInterfaceView:
    """Verify the ``view=GraphView.PUBLIC_API`` PlantUML export
    hides private members, removes concept nodes and file nodes,
    and collapses external dependencies into simple package
    declarations.

    This view shows only the public-facing API surface — no private
    methods/attributes, no concepts, no files, no external dependency
    details."""

    @pytest.fixture(scope="class")
    def public_puml(self, codegraph_graph):
        """Load the public-only PlantUML text produced by the session fixture."""
        puml_path = _CODEGRAPH_OUTPUT / "cpp_sqlite_preservation_one_hop_public.puml"
        assert puml_path.exists(), f"Public PUML not found at {puml_path}"
        text = puml_path.read_text(encoding="utf-8")
        print(f"\n  Public PUML: {len(text.splitlines())} lines")
        return text

    # ------------------------------------------------------------------
    # Package assertions: PUBLIC_API hides ALL external deps entirely
    # ------------------------------------------------------------------

    def test_no_external_packages(self, public_puml):
        """External dependency packages (std, boost, spdlog, sqlite3)
        do NOT appear in the public API view."""
        for pkg in ("std", "boost", "spdlog", "sqlite3"):
            assert f'package "{pkg}" as {pkg}' not in public_puml, (
                f"External package {pkg} should not appear in public API view"
            )

    def test_no_external_references_anywhere(self, public_puml):
        """No external dependency (std, boost, spdlog, sqlite3) may
        appear as a PlantUML package, standalone element, or edge
        target in the public API view.

        C++ type names inside member signatures (e.g.
        ``std::string``) are fine — they are display text, not
        PlantUML structural elements."""
        import re

        external_pkgs = {"std", "boost", "spdlog", "sqlite3"}

        for line in public_puml.splitlines():
            stripped = line.strip()

            # 1. Package declarations
            for pkg in external_pkgs:
                if f'package "{pkg}"' in stripped:
                    raise AssertionError(
                        f"External package declared in public view: {stripped!r}"
                    )

            # 2. Standalone elements with external aliases:
            #    class "..." as std__vector {  or  class "sqlite3" as sqlite3 { ...
            m = re.match(r'(?:class|interface|enum|union)\s+"[^"]*"\s+as\s+(\S+)', stripped)
            if m:
                alias = m.group(1)
                for pkg in external_pkgs:
                    if alias == pkg or alias.startswith(pkg + "__"):
                        raise AssertionError(
                            f"External element in public view: {stripped!r}"
                        )

            # 3. Edge targets — any arrow line whose target is external
            m = re.match(
                r'(?:\S+)\s+(?:<\|--|\.\.\|>|\.\.>|-->|o--|\*--)\s+(\S+)\s+:',
                stripped,
            )
            if m:
                tgt = m.group(1)
                for pkg in external_pkgs:
                    if tgt == pkg or tgt.startswith(pkg + "__"):
                        raise AssertionError(
                            f"External edge target in public view: {stripped!r}"
                        )

    def test_no_individual_std_types(self, public_puml):
        """Individual std types are collapsed into the ``std`` package."""
        import re
        collapsed_lines = set(public_puml.splitlines())
        for extern in ("std__vector", "std__optional", "std__runtime_error",
                        "std__unique_ptr", "std__shared_ptr", "std__mutex"):
            pattern = re.compile(
                r'(?:^|\b)' + re.escape(extern) + r'(?:\b|$)'
            )
            for line in collapsed_lines:
                if pattern.search(line):
                    if line.startswith("cpp_sqlite__") and ("<|" in line or "..>" in line):
                        continue
                    if " as " + extern in line:
                        raise AssertionError(
                            f"Individual type {extern} appears as element: {line}"
                        )
                    if "..> " + extern in line or "--> " + extern in line or "<|-- " + extern in line:
                        raise AssertionError(
                            f"Individual type {extern} appears as edge target: {line}"
                        )

    def test_no_individual_sqlite3_functions(self, public_puml):
        """Individual sqlite3 functions are collapsed."""
        for func in ("sqlite3_step", "sqlite3_bind_int64",
                      "sqlite3_finalize", "sqlite3_prepare_v2"):
            assert func not in public_puml, (
                f"Individual function {func} should be collapsed"
            )

    # ------------------------------------------------------------------
    # Private-member assertions
    # ------------------------------------------------------------------

    def test_no_private_member_lines(self, public_puml):
        """No private member lines (``-`` prefix) appear in the
        public-only view."""
        for line in public_puml.splitlines():
            stripped = line.strip()
            if stripped and stripped[0] == "-":
                # Allow ``-`` in arrow symbols like <|-- and -->
                if "<|" in stripped or "--" in stripped:
                    continue
                raise AssertionError(
                    f"Private member line found in public view: {line.strip()!r}"
                )

    def test_public_view_has_no_private_members_in_classes(self, public_puml):
        """Class bodies in the public view contain only public/protected
        members (``+`` or ``#`` prefix), never private (``-``) members."""
        # Extract all member lines: lines starting with +, -, or # after
        # whitespace (inside class/enum/package bodies).
        member_lines = [
            L.strip() for L in public_puml.splitlines()
            if L.strip() and L.strip()[0] in ("+", "-", "#")
        ]
        private_lines = [L for L in member_lines if L[0] == "-"]
        assert len(private_lines) == 0, (
            f"Found {len(private_lines)} private member lines in public view:\n"
            + "\n".join(f"  {L}" for L in private_lines[:10])
        )

    def test_no_member_aliases_as_arrow_targets(self, public_puml):
        """No arrow target should be a member alias.

        The check is structural: every arrow target must be an alias
        declared as a standalone element (class, interface, enum,
        union, package, or note) in the public view."""
        import re
        declared = set()
        for line in public_puml.splitlines():
            m = re.match(
                r'(?:class|interface|enum|union|package|note)\s+"[^"]*"\s+as\s+(\S+)',
                line.strip(),
            )
            if m:
                declared.add(m.group(1))
        arrow_pattern = re.compile(
            r'(\S+)\s+(<\|--|\.\.\|>|\.\.>|-->|o--|\*--)\s+(\S+)\s+: '
        )
        for line in public_puml.splitlines():
            m = arrow_pattern.search(line)
            if m and m.group(3) not in declared:
                raise AssertionError(
                    f"Public-view arrow target is not a declared element "
                    f"(member alias?): {line.strip()!r}"
                )

    # ------------------------------------------------------------------
    # Relationship assertions
    # ------------------------------------------------------------------

    def test_no_external_edges(self, public_puml):
        """No edges target any external package (std, boost, spdlog,
        sqlite3) in the public API view."""
        for pkg in ("std", "boost", "spdlog", "sqlite3"):
            import re
            pattern = re.compile(rf'\b{re.escape(pkg)}\b.*\s+:\s')
            for line in public_puml.splitlines():
                if pattern.search(line):
                    raise AssertionError(
                        f"External edge found in public API view: {line.strip()!r}"
                    )

    def test_no_depends_on_to_individual_types(self, public_puml):
        """No ``depends_on`` arrows target individual external type aliases."""
        import re
        deps = re.findall(
            r'^\.\.>\s+(\S+)\s+:\s+depends_on',
            public_puml, re.MULTILINE,
        )
        individual = [d for d in deps if "__" in d]
        individual_external = [d for d in individual
                               if not d.startswith("cpp_sqlite__")]
        assert len(individual_external) == 0, (
            f"External individual type targets found: {individual_external}"
        )

    # ------------------------------------------------------------------
    # Size comparison
    # ------------------------------------------------------------------

    def test_public_view_smaller_than_collapsed(self, public_puml):
        """The public-only view is smaller than the collapsed view
        (fewer members = fewer lines)."""
        collapsed_path = _CODEGRAPH_OUTPUT / "cpp_sqlite_preservation_one_hop_collapsed.puml"
        collapsed_puml = collapsed_path.read_text(encoding="utf-8")

        public_members = len([
            L for L in public_puml.splitlines()
            if L.strip() and L.strip()[0] in ("+", "-", "#")
        ])
        collapsed_members = len([
            L for L in collapsed_puml.splitlines()
            if L.strip() and L.strip()[0] in ("+", "-", "#")
        ])
        assert public_members <= collapsed_members, (
            f"Public view has {public_members} members, "
            f"collapsed has {collapsed_members} — "
            f"public should have fewer or equal"
        )
        print(f"\n  Collapsed members: {collapsed_members}, Public members: {public_members}")

    # ------------------------------------------------------------------
    # Fidelity: public edges are a subset of collapsed edges
    # ------------------------------------------------------------------

    def test_public_edges_are_subset_of_collapsed(self, public_puml):
        """Every edge in the public-only view is also present in the
        collapsed view.  Hiding private members and external deps
        should only remove edges, never add new ones.

        All public-view edge targets are project-internal (no external
        packages)."""
        import re

        collapsed_path = _CODEGRAPH_OUTPUT / "cpp_sqlite_preservation_one_hop_collapsed.puml"
        collapsed_puml = collapsed_path.read_text(encoding="utf-8")

        def _parse(puml):
            edges = set()
            for L in puml.splitlines():
                m = re.match(
                    r'(\S+)\s+(<\|--|\.\.\|>|\.\.>|-->|o--|\*--)\s+(\S+)\s+:\s+(\S+)',
                    L,
                )
                if m:
                    edges.add((m.group(1), m.group(2), m.group(3), m.group(4)))
            return edges

        collapsed_edges = _parse(collapsed_puml)
        public_edges = _parse(public_puml)

        # Assert no external package targets
        external_pkgs = {"std", "boost", "spdlog", "sqlite3", "detail", "fmt", "mp_cond"}
        for _, _, tgt, _ in public_edges:
            assert tgt not in external_pkgs, (
                f"Public view edge targets external package: {tgt}"
            )

        spurious: list[tuple] = []
        for src, arrow, tgt, label in public_edges:
            if (src, arrow, tgt, label) not in collapsed_edges:
                spurious.append((src, arrow, tgt, label))

        assert len(spurious) == 0, (
            f"{len(spurious)} edges in public view not present in collapsed:\n"
            + "\n".join(
                f"  {s} {a} {t} : {l}" for s, a, t, l in spurious[:10]
            )
        )

    def test_all_public_edges_internal(self, public_puml):
        """Every edge in the public API view targets a project-internal
        element (cpp_sqlite__* or DAOBase — no external packages)."""
        import re
        for line in public_puml.splitlines():
            m = re.match(
                r'(\S+)\s+(<\|--|\.\.\|>|\.\.>|-->|o--|\*--)\s+(\S+)\s+:',
                line,
            )
            if m:
                tgt_alias = m.group(3)
                assert (
                    tgt_alias.startswith("cpp_sqlite__")
                    or tgt_alias == "DAOBase"
                    or tgt_alias.startswith("DAOBase__")
                ), (
                    f"Public-view edge targets non-project element: {line.strip()!r}"
                )

    # ------------------------------------------------------------------
    # Concept node assertions
    # ------------------------------------------------------------------

    def test_no_concept_nodes(self, public_puml):
        """Concept nodes (``<<concept>>`` stereotype) are removed from
        the public API view."""
        assert "<<concept>>" not in public_puml, (
            "Concept nodes should not appear in public API view"
        )

    def test_no_concept_edges(self, public_puml):
        """Edges involving concept nodes (e.g. ``constrains``) are
        removed from the public API view."""
        assert "constrains" not in public_puml, (
            "Concept constrains edges should not appear in public API view"
        )

    # ------------------------------------------------------------------
    # File node assertions
    # ------------------------------------------------------------------

    def test_no_file_nodes(self, public_puml):
        """File nodes (``note`` elements) are removed from the public
        API view."""
        import re
        note_lines = [
            L for L in public_puml.splitlines()
            if re.match(r'^\s*note\s+"', L)
        ]
        assert len(note_lines) == 0, (
            f"Found {len(note_lines)} file note lines in public view"
        )

    def test_no_includes_edges(self, public_puml):
        """File-reference edges (``includes``) are removed from the
        public API view."""
        assert " : includes" not in public_puml, (
            "Includes edges should not appear in public API view"
        )


class TestClassScopedView:
    """Verify the ``scope_class`` PlantUML export produces a
    class-centric dependency view.

    When scoped to ``cpp_sqlite::Database``:
    - Database shows ALL members (including private) in full detail.
    - Dependent classes (Transaction, DataAccessObject, DAOBase)
      only show the specific members Database calls.
    - External dependencies (std, boost, spdlog, sqlite3) are
      collapsed into packages.
    - File nodes and concept nodes are omitted.
    """

    @classmethod
    @pytest.fixture(scope="class")
    def scoped_database_puml(cls):
        """Generate the scoped PlantUML for Database on the fly."""
        import json as _json
        from codegraph.graph import LayerGraph
        from codegraph.export.plantuml import PlantUMLExporter

        json_path = _UNIT_TEST_DATA / "cpp_sqlite_preservation_one_hop.json"
        data = _json.loads(json_path.read_text(encoding="utf-8"))
        graph = LayerGraph.deserialize(data)
        return PlantUMLExporter(
            graph, fields="all", scope_class="cpp_sqlite::Database"
        ).export()

    # ------------------------------------------------------------------
    # Target class assertions
    # ------------------------------------------------------------------

    def test_database_shows_all_members(self, scoped_database_puml):
        """Database renders as a normal class with all members
        (including private) inline — signatures and parameters in the
        class body, not as standalone nodes."""
        assert 'class "Database" as cpp_sqlite__Database {' in scoped_database_puml
        for name in ("getDAO", "flushAllDAOs", "select", "insert",
                     "getRawDB", "isInTransaction", "withTransaction",
                     "daos_", "daoCreationOrder_", "pLogger_", "db_"):
            assert name in scoped_database_puml, (
                f"Database member {name} missing from class body"
            )
        # Full signatures with parameters render in the member lines.
        assert "+getDAO(): DataAccessObject < T > &" in scoped_database_puml
        assert "+withTransaction(Func &&func): void" in scoped_database_puml
        assert "+Database(std::string url, bool allowWrite" in scoped_database_puml
        # Private attributes marked with '-'
        assert "-db_: std::unique_ptr< sqlite3" in scoped_database_puml

    def test_database_rendered_as_class(self, scoped_database_puml):
        """The scoped class is a normal ``class`` element, not the
        atomic package-of-member-nodes style."""
        assert 'class "Database" as cpp_sqlite__Database {' in scoped_database_puml
        assert 'package "Database"' not in scoped_database_puml

    def test_transaction_only_shows_commit(self, scoped_database_puml):
        """Transaction class only exposes ``commit()`` — the only
        method Database actually calls."""
        assert "commit()" in scoped_database_puml
        for hidden in ("executeSQL", "rollback", "getSavepointName",
                       "isActive", "isActive_", "savepointName_"):
            assert hidden not in scoped_database_puml, (
                f"Transaction member {hidden} should not appear in scoped view"
            )

    def test_data_access_object_no_members(self, scoped_database_puml):
        """DataAccessObject appears (Database DEPENDS_ON it) but with
        no members — Database doesn't invoke specific methods."""
        assert "DataAccessObject" in scoped_database_puml
        for hidden in ("prepareSelectStatements", "selectCacheById",
                       "selectAll", "prepareSQLStatements",
                       "generateSelectAllSQL", "generateInsertSQL",
                       "getTableName", "generateCreateTableSQL",
                       "incrementIdCounter", "executeCreateStmt",
                       "addToBuffer"):
            assert hidden not in scoped_database_puml, (
                f"DataAccessObject member {hidden} should not appear"
            )

    # ------------------------------------------------------------------
    # External dependency assertions (collapsed to packages)
    # ------------------------------------------------------------------

    def test_external_packages_are_collapsed(self, scoped_database_puml):
        """External dependencies appear as collapsed packages."""
        for pkg in ("std", "boost", "spdlog", "sqlite3"):
            assert f'package "{pkg}" as {pkg}' in scoped_database_puml, (
                f"Missing external package: {pkg}"
            )

    def test_no_individual_external_types(self, scoped_database_puml):
        """Individual external types are NOT emitted as standalone elements."""
        import re
        for line in scoped_database_puml.splitlines():
            stripped = line.strip()
            m = re.match(
                r'(?:class|interface|enum|union)\s+"[^"]*"\s+as\s+(\S+)',
                stripped,
            )
            if m:
                alias = m.group(1)
                for prefix in ("std__", "boost__", "spdlog__", "sqlite3_"):
                    if alias.startswith(prefix):
                        raise AssertionError(
                            f"Individual external type in scoped view: {stripped!r}"
                        )

    def test_external_edges_are_to_packages(self, scoped_database_puml):
        """Edges redirect to package aliases, aggregated to the Database
        class (members render inline, so edges originate from the class)."""
        assert "cpp_sqlite__Database ..> boost : depends_on" in scoped_database_puml
        assert "cpp_sqlite__Database ..> spdlog : depends_on" in scoped_database_puml
        assert "cpp_sqlite__Database ..> sqlite3 : depends_on" in scoped_database_puml
        assert "cpp_sqlite__Database ..> std : depends_on" in scoped_database_puml

    # ------------------------------------------------------------------
    # Edge assertions
    # ------------------------------------------------------------------

    def test_database_edges_are_present(self, scoped_database_puml):
        """Edges originate from the Database class (members are inline)."""
        edges = [
            "cpp_sqlite__Database ..> cpp_sqlite__Transaction : invokes",
            "cpp_sqlite__Database ..> cpp_sqlite__DataAccessObject : depends_on",
            "cpp_sqlite__Database ..> DAOBase : depends_on",
        ]
        for edge in edges:
            assert edge in scoped_database_puml, (
                f"Missing edge: {edge}"
            )

    def test_no_file_nodes(self, scoped_database_puml):
        """No file nodes in scoped view."""
        import re
        note_lines = [
            L for L in scoped_database_puml.splitlines()
            if re.match(r'^\s*note\s+"', L)
        ]
        assert len(note_lines) == 0

    def test_no_concept_nodes(self, scoped_database_puml):
        """No concept nodes in scoped view."""
        assert "<<concept>>" not in scoped_database_puml

    # ------------------------------------------------------------------
    # SVG rendering
    # ------------------------------------------------------------------

    def test_scoped_svg_renders(self, scoped_database_puml):
        """The scoped PlantUML can be rendered to a valid SVG.

        Uses ``render_plantuml_to_svg``, which validates the output —
        PlantUML exits 0 even on syntax errors and emits an error-page
        SVG instead, so a plain subprocess + ``<svg>`` checks would
        pass on a broken diagram."""
        import shutil
        import tempfile
        from pathlib import Path

        from codegraph.export.plantuml import render_plantuml_to_svg

        if not shutil.which("plantuml"):
            pytest.skip("plantuml CLI not found on PATH")

        with tempfile.TemporaryDirectory() as tmpdir:
            puml_path = Path(tmpdir) / "scoped_database.puml"
            puml_path.write_text(scoped_database_puml, encoding="utf-8")
            svg_path = render_plantuml_to_svg(puml_path, timeout=120)
            # Copy to output dir for inspection
            output_svg = _CODEGRAPH_OUTPUT / "scoped_database.svg"
            shutil.copy(str(svg_path), str(output_svg))
            print(f"\n  Scoped SVG: {output_svg} ({svg_path.stat().st_size:,} bytes)")
