"""PlantUML visualisation tests for the doxygen-index dogfood graph.

Verifies that the PlantUML exporter produces valid class-diagram
syntax with expected elements and relationships for this repository's
own Python source: the parser class hierarchy, the PageType enum, the
module namespace tree, and invokes/depends_on/inherits arrows.

The ``.puml`` files are generated by the session-scoped
``codegraph_graph`` fixture in conftest alongside JSON and HTML
(``codegraph_index_one_hop*.puml``).

Requirements: only the ``doxygen-index`` CLI on PATH; SVG rendering
needs the ``plantuml`` binary (skipped if absent).
"""

from __future__ import annotations

from pathlib import Path
import shutil

import pytest

from .artifacts import CODEGRAPH_OUTPUT as _CODEGRAPH_OUTPUT
from .artifacts import UNIT_TEST_DATA



class TestPlantUMLExport:
    """Verify the PlantUML export contains expected elements and
    relationships for the dogfood as-built graph."""

    @pytest.fixture(scope="class")
    def puml_text(self, codegraph_graph):
        """Load the PlantUML text generated by the session fixture."""
        puml_path = _CODEGRAPH_OUTPUT / "codegraph_index_one_hop.puml"
        assert puml_path.exists(), f"PUML not found at {puml_path}"
        return puml_path.read_text(encoding="utf-8")

    @pytest.fixture(scope="class")
    def puml_lines(self, puml_text):
        """Split the PlantUML text into non-empty, non-comment lines."""
        return [
            L for L in puml_text.split("\n")
            if L.strip() and not L.strip().startswith("'")
            and not L.strip().startswith("@")
            and not L.strip().startswith("skinparam")
        ]

    # ------------------------------------------------------------------
    # Structure
    # ------------------------------------------------------------------

    def test_puml_has_startuml(self, puml_text):
        """The PlantUML output is wrapped in @startuml / @enduml."""
        assert "@startuml" in puml_text
        assert "@enduml" in puml_text

    def test_puml_has_namespace_packages(self, puml_lines):
        """Nested package declarations mirror the module tree."""
        assert any('package "codegraph_index"' in L for L in puml_lines)
        assert any('package "parser"' in L for L in puml_lines)
        assert any('package "base"' in L for L in puml_lines)
        assert any('package "cppreference"' in L for L in puml_lines)

    # ------------------------------------------------------------------
    # Element assertions
    # ------------------------------------------------------------------

    def test_puml_has_interface_and_parsers(self, puml_lines):
        """The parser hierarchy is present: LanguageParser interface +
        both concrete parsers."""
        assert any('interface "LanguageParser"' in L for L in puml_lines), (
            "missing LanguageParser interface"
        )
        assert any('class "CppParser"' in L for L in puml_lines)
        assert any('class "PythonParser"' in L for L in puml_lines)

    def test_puml_has_enum(self, puml_lines):
        """PageType renders as an enum with all six values."""
        assert any('enum "PageType"' in L for L in puml_lines), (
            "missing PageType enum"
        )
        enum_block = False
        values = []
        for L in puml_lines:
            if 'enum "PageType"' in L:
                enum_block = True
                continue
            if enum_block and L.strip().startswith("}"):
                break
            if enum_block:
                values.append(L.strip())
        assert values == [
            "HEADER", "CLASS", "MEMBER", "FREE_FUNCTION", "NAMESPACE", "SKIP",
        ], values

    def test_puml_has_member_lines(self, puml_lines):
        """Class bodies carry public members (PageInfo attributes etc.)."""
        member_lines = [L for L in puml_lines if L.strip().startswith("+")]
        assert len(member_lines) > 5, (
            f"expected public members in class bodies, got {len(member_lines)}"
        )
        assert any("page_type: PageType" in L for L in member_lines)

    # ------------------------------------------------------------------
    # Relationship assertions
    # ------------------------------------------------------------------

    def test_puml_has_invokes_arrows(self, puml_lines):
        invokes = [L for L in puml_lines if " : invokes" in L]
        assert len(invokes) > 0, "Expected INVOKES arrows"

    def test_puml_has_depends_on_arrows(self, puml_lines):
        deps = [L for L in puml_lines if " : depends_on" in L]
        assert len(deps) > 0, "Expected DEPENDS_ON arrows"

    def test_puml_has_inheritance(self, puml_lines):
        """Both concrete parsers inherit from the LanguageParser interface."""
        # Literal nodes may contain snippets of PlantUML used by other tests;
        # only count actual arrow statements targeting LanguageParser.
        inherit_lines = [
            L for L in puml_lines
            if not L.lstrip().startswith(('class "', 'package "'))
            and " <|-- " in L
            and "LanguageParser : inherits_from" in L
        ]
        assert len(inherit_lines) == 2, (
            f"expected 2 inheritance arrows, got {len(inherit_lines)}"
        )
        for L in inherit_lines:
            assert "LanguageParser" in L
        assert any("CppParser" in L for L in inherit_lines)
        assert any("PythonParser" in L for L in inherit_lines)

    def test_collapsed_puml_artifact_generated(self, codegraph_graph):
        """The whole-graph inspection artifact is available as PlantUML.

        Whole-graph Graphviz rendering is intentionally not part of the
        session fixture: this view retains every project member and is too
        large for a stable layout.  Scoped PlantUML tests render and validate
        bounded SVGs separately.
        """
        puml_path = _CODEGRAPH_OUTPUT / "codegraph_index_one_hop_collapsed.puml"
        text = puml_path.read_text(encoding="utf-8", errors="replace")
        assert "@startuml" in text
        assert "LanguageParser" in text


class TestPublicApiView:
    """PUBLIC_API hides private members but keeps the public surface."""

    @pytest.fixture(scope="class")
    def public_puml(self, codegraph_graph):
        puml_path = _CODEGRAPH_OUTPUT / "codegraph_index_one_hop_public.puml"
        assert puml_path.exists(), f"PUML not found at {puml_path}"
        return puml_path.read_text(encoding="utf-8")

    def test_public_view_excludes_private_methods(self, public_puml):
        """Private methods (underscore-prefixed class members) are hidden.

        NOTE: PUBLIC_API filters by *member* visibility — private
        module-level functions (e.g. ``_scan_file_catch_clauses``) are
        not class members, so they legitimately remain.  Assert against
        private methods of CppParser instead.
        """
        member_lines = [L.strip() for L in public_puml.splitlines()
                        if L.lstrip().startswith(("+", "-", "#"))]
        assert not any("_parse_class_compound" in L for L in member_lines), (
            "private method should be hidden in PUBLIC_API view"
        )
        assert not any("_parse_function_member" in L for L in member_lines)

    def test_public_view_keeps_public_surface(self, public_puml):
        """Public interface methods and key classes remain visible."""
        assert 'interface "LanguageParser"' in public_puml
        assert "parse_source_dir" in public_puml
        assert 'class "CppParser"' in public_puml
        assert 'enum "PageType"' in public_puml


class TestCollapsedView:
    """COLLAPSED collapses dependency packages to package level.

    The dogfood graph is single-source — there are no dependency
    packages to collapse — so the collapsed view is structurally
    identical to FULL (documented behaviour, asserted explicitly so a
    future change to either side is noticed).
    """

    @pytest.fixture(scope="class")
    def collapsed_puml(self, codegraph_graph):
        puml_path = _CODEGRAPH_OUTPUT / "codegraph_index_one_hop_collapsed.puml"
        assert puml_path.exists(), f"PUML not found at {puml_path}"
        return puml_path.read_text(encoding="utf-8")

    @pytest.fixture(scope="class")
    def full_puml(self, codegraph_graph):
        puml_path = _CODEGRAPH_OUTPUT / "codegraph_index_one_hop.puml"
        assert puml_path.exists(), f"PUML not found at {puml_path}"
        return puml_path.read_text(encoding="utf-8")

    def test_collapsed_has_namespace_packages(self, collapsed_puml):
        assert 'package "codegraph_index"' in collapsed_puml
        assert 'interface "LanguageParser"' in collapsed_puml

    def test_collapsed_has_no_file_nodes(self, collapsed_puml):
        """File nodes never appear as diagram elements."""
        file_notes = [
            L for L in collapsed_puml.splitlines()
            if L.lstrip().startswith('note "') and ".py" in L
        ]
        assert not file_notes, (
            "file nodes should not appear in COLLAPSED view"
        )

    def test_collapsed_groups_discovered_dependencies(self, collapsed_puml, full_puml):
        """Dependencies discovered while indexing tests collapse to packages."""
        assert 'package "sqlite3" as sqlite3' in collapsed_puml
        assert 'package "sqlite3" as sqlite3' not in full_puml
        assert collapsed_puml != full_puml


class TestScopedPlantUMLExport:
    """Verify the class-scoped PlantUML export for PythonParser.

    Mirrors the cpp-sqlite ``scoped_database`` section: the focal
    class renders as a package with each member as a standalone node,
    dependent types appear with only what the class touches, and the
    result is written to ``python_parser_scoped.svg`` for inspection.
    """

    SCOPE_QN = "codegraph_index.parser.python._parser.PythonParser"

    @classmethod
    @pytest.fixture(scope="class")
    def scoped_python_parser_puml(cls):
        """Generate the scoped PlantUML for PythonParser on the fly."""
        import json as _json
        from codegraph.graph import LayerGraph
        from codegraph.export.plantuml import PlantUMLExporter

        json_path = UNIT_TEST_DATA / "codegraph_index_one_hop.json"
        data = _json.loads(json_path.read_text(encoding="utf-8"))
        graph = LayerGraph.deserialize(data)
        return PlantUMLExporter(
            graph, fields="all", scope_class=cls.SCOPE_QN
        ).export()

    # ------------------------------------------------------------------
    # Target class assertions
    # ------------------------------------------------------------------

    def test_python_parser_shows_all_members(self, scoped_python_parser_puml):
        """PythonParser renders as a normal class with all methods
        inline — signatures and parameters in the class body, not as
        standalone nodes (the atomic style was too busy)."""
        assert (
            'class "PythonParser" as '
            'codegraph_index_parser_python__parser_PythonParser {'
        ) in scoped_python_parser_puml
        for member in ("parse_source_dir", "post_process",
                       "_register_package", "_parse_python_file"):
            assert member in scoped_python_parser_puml, (
                f"missing member: {member}"
            )
        # Full signatures with parameters render in the member lines.
        assert (
            "+parse_source_dir(self, source_dir: Path, source: str, "
            "result: ParseResult"
        ) in scoped_python_parser_puml
        assert "+post_process(self, result: ParseResult): None" in scoped_python_parser_puml
        # Private methods shown with '-' inside the class body.
        assert "-_parse_python_file(" in scoped_python_parser_puml
        # No standalone member nodes (the old atomic style).
        assert 'class "parse_source_dir"' not in scoped_python_parser_puml
        assert 'package "PythonParser"' not in scoped_python_parser_puml

    def test_python_parser_inherits_language_parser(self, scoped_python_parser_puml):
        """The inheritance edge to the base interface is present AND the
        base renders as a real element (no phantom arrow target)."""
        assert (
            "codegraph_index_parser_python__parser_PythonParser <|-- "
            "codegraph_index_parser_base_LanguageParser : inherits_from"
        ) in scoped_python_parser_puml
        assert 'interface "LanguageParser"' in scoped_python_parser_puml

    def test_no_phantom_nodes(self, scoped_python_parser_puml):
        """Every arrow endpoint resolves to an emitted element.

        Regression guard: arrows to 2-hop neighbours (targets invoked
        by 1-hop neighbours) used to be emitted without the target
        element, so PlantUML synthesized phantom nodes floating
        outside the namespace tree (e.g.
        ``codegraph_index_cppreference__parse_html``).  The exporter now
        drops arrows whose endpoint was not emitted.
        """
        import re

        aliases = set(
            m.group(1)
            for m in re.finditer(
                r'^\s*(?:class|interface|enum|union|package)\s+"[^"]*"\s+as\s+(\S+)',
                scoped_python_parser_puml, re.M,
            )
        )
        arrows = [
            (m.group(1), m.group(2))
            for m in re.finditer(
                r"^(\S+)\s+(?:\.\.>|<\|--|\*--|\.\.\|>|-->|o--)\s+(\S+)",
                scoped_python_parser_puml, re.M,
            )
        ]
        dangling = [(s, t) for s, t in arrows
                    if s not in aliases or t not in aliases]
        assert not dangling, f"{len(dangling)} phantom arrow endpoints"

        # The concrete 2-hop strays from the original bug are gone.
        assert "_parse_html" not in scoped_python_parser_puml
        assert "_synthesize_namespaces" not in scoped_python_parser_puml

    def test_dependent_types_in_scoped_view(self, scoped_python_parser_puml):
        """Neighbours the class depends on appear: the ParseResult type
        (DEPENDS_ON) and the helper functions it invokes."""
        assert "ParseResult" in scoped_python_parser_puml
        assert "is_excluded" in scoped_python_parser_puml
        assert "derive_invokes" in scoped_python_parser_puml

    def test_scoped_has_invokes_and_depends_on_arrows(
        self, scoped_python_parser_puml
    ):
        assert " : invokes" in scoped_python_parser_puml
        assert " : depends_on" in scoped_python_parser_puml

    def test_scoped_no_file_nodes(self, scoped_python_parser_puml):
        """No file nodes in the scoped view."""
        assert ".py" not in scoped_python_parser_puml

    # ------------------------------------------------------------------
    # SVG rendering
    # ------------------------------------------------------------------

    def test_scoped_svg_renders(self, scoped_python_parser_puml):
        """The scoped PlantUML can be rendered to a valid SVG, copied to
        the output dir for inspection."""
        import shutil
        import tempfile

        from codegraph.export.plantuml import render_plantuml_to_svg

        if not shutil.which("plantuml"):
            pytest.skip("plantuml CLI not found on PATH")

        with tempfile.TemporaryDirectory() as tmpdir:
            puml_path = Path(tmpdir) / "python_parser_scoped.puml"
            puml_path.write_text(scoped_python_parser_puml, encoding="utf-8")
            svg_path = render_plantuml_to_svg(puml_path, timeout=120)
            output_svg = _CODEGRAPH_OUTPUT / "python_parser_scoped.svg"
            shutil.copy(str(svg_path), str(output_svg))
            print(f"\n  Scoped SVG: {output_svg} ({svg_path.stat().st_size:,} bytes)")

        text = output_svg.read_text(encoding="utf-8", errors="replace")
        assert "PythonParser" in text
