#!/usr/bin/env python3
"""Sync the codegen golden design fixture between repos (R1).

The canonical design LayerGraph lives in the sister repo
``doxygen-dependency-parser/tests/data/design_layergraph.json``.  The
codegraph repo keeps a reviewed golden at
``tests/codegen/golden/design_layergraph.json`` plus the fresh
generator output at ``tests/pipelines/unit_test_data/design_layergraph.json``
(written by ``tests/pipelines/test_design_migration_manager.py``).

Actions
-------
push   generated pipeline copy → sister repo  → golden (refresh all)
pull   sister repo → golden (sister regenerated; pull the new canonical)
check  byte-compare all three; fail on drift

Usage::

    python scripts/sync_codegen_fixtures.py check
    python scripts/sync_codegen_fixtures.py push
"""

from __future__ import annotations

import hashlib
import json
import re
import shutil
import sys
from collections import Counter
from pathlib import Path

from codegraph.identity import CanonicalIdentity

ROOT = Path(__file__).resolve().parent.parent
# The actual workspace repository.  Keep this spelling explicit: macOS may
# resolve a differently-cased path while tooling and provenance records do not.
SISTER = ROOT.parent / "Doxygen-Dependency-Parser"

PIPELINE_COPY = ROOT / "tests/pipelines/unit_test_data/design_layergraph.json"
GOLDEN = ROOT / "tests/codegen/golden/design_layergraph.json"
SISTER_CANONICAL = SISTER / "tests/data/design_layergraph.json"

#: The cpp-sqlite one-hop as-built graph — generated by the sister repo's
#: ``tests/cpp_sqlite_integration/`` suite (``LayerGraph.from_backend`` +
#: ``serialize(fields="all")``).  Here it is a pinned input for
#: ``tests/codegen/test_cpp_sqlite_one_hop.py``; the sister repo is the
#: canonical source (pull to adopt a fresh export).
ONE_HOP = ROOT / "tests/unit_test_data/cpp_sqlite_one_hop.json"
SISTER_ONE_HOP = SISTER / "tests/unit_test_data/cpp_sqlite_one_hop.json"

#: The implementation-bearing export (``serialize(fields="all",
#: export_implementation=True)``): MethodNodes carry their implementation
#: ``body``/``body_file`` and INCLUDES edges carry the include spelling —
#: the semantic-reconstruction input for
#: ``tests/codegen/test_cpp_sqlite_one_hop.py::TestImplementationExport``.
IMPL = ROOT / "tests/unit_test_data/cpp_sqlite_one_hop_impl.json"
SISTER_IMPL = SISTER / "tests/unit_test_data/cpp_sqlite_one_hop_impl.json"

#: The original cpp-sqlite sources the byte-for-byte suite regenerates
#: and compares against (committed copies of
#: ``sister/tests/fixtures/cpp-sqlite/``).
IMPL_SRC = ROOT / "tests/unit_test_data/cpp_sqlite_impl_src"
SISTER_FIXTURE_SRC = SISTER / "tests/fixtures/cpp-sqlite"

# The canonical as-built projection is refreshed explicitly by
# ``scripts/refresh_cpp_sqlite_as_built.py``.  It is checked here even though
# it has no sister-repository copy: a sync gate must not bless a legacy
# endpoint in the pipeline input.
COMPLETE_GRAPH = (
    ROOT / "tests" / "pipelines" / "data" / "cpp_sqlite"
    / "codegraph_as_built.json"
)
#: The 14-file production manifest + the provenance record pinning the
#: golden source-copy hashes (``check`` verifies, ``pull`` re-records).
MANIFEST = ROOT / "tests/codegen/cpp_sqlite_roundtrip_manifest.txt"
PROVENANCE = ROOT / "tests/codegen/cpp_sqlite_roundtrip_provenance.md"

#: The two test files stay outside source byte-fidelity (constraint 3).
TEST_FILES = frozenset({
    "tests/fixtures/cpp-sqlite/cpp_sqlite/test/testDatabase.cpp",
    "tests/fixtures/cpp-sqlite/cpp_sqlite/test/testDatabase.hpp",
})

_FORBIDDEN_NODE_FIELDS = frozenset({
    "uid", "refid", "compound_refid", "member_refid", "parent_refid",
    "child_refid", "from_refid", "to_refid",
})
_FORBIDDEN_EDGE_FIELDS = frozenset({
    "uid", "target_uid", "refid", "from_refid", "to_refid",
})

# Endpoint policy is intentionally fixture-family specific.  All synchronized
# fixtures must use canonical endpoints; a target omitted from a projection is
# represented by a canonical key plus ``external: true``.
_ENDPOINT_POLICY: dict[str, frozenset[str]] = {
    "design_layergraph.json": frozenset({
        "resolves in-document",
        "canonical external target",
    }),
    "cpp_sqlite_one_hop.json": frozenset({
        "resolves in-document",
        "canonical external target",
    }),
    "cpp_sqlite_one_hop_impl.json": frozenset({
        "resolves in-document",
        "canonical external target",
    }),
    "codegraph_as_built.json": frozenset({
        "resolves in-document",
        "canonical external target",
    }),
}


def _production_relpaths() -> list[str]:
    """The 14 production paths from the manifest (relative to IMPL_SRC)."""
    return [
        line.strip()
        for line in MANIFEST.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]


def _provenance_hashes() -> dict[str, str]:
    """Parse the golden source-copy hashes recorded in the provenance file."""
    if not PROVENANCE.is_file():
        return {}
    production_paths = set(_production_relpaths())
    hashes: dict[str, str] = {}
    in_block = False
    for line in PROVENANCE.read_text(encoding="utf-8").splitlines():
        if line.strip() == "```":
            in_block = not in_block
            continue
        if not in_block:
            continue
        parts = line.split(None, 1)
        if (
            len(parts) == 2
            and re.fullmatch(r"[0-9a-f]{64}", parts[0])
            and parts[1].strip() in production_paths
        ):
            hashes[parts[1].strip()] = parts[0]
    return hashes


def _write_provenance_hashes(hashes: dict[str, str]) -> None:
    """Rewrite every source-hash block (``pull`` only).

    A provenance document may contain more than one hash block.  Update only
    fenced blocks containing strict hash/path records so path-only manifest
    blocks remain documentation rather than being converted into hashes.
    """
    lines = PROVENANCE.read_text(encoding="utf-8").splitlines()
    production_paths = set(_production_relpaths())
    ranges: list[tuple[int, int]] = []
    start: int | None = None
    for idx, line in enumerate(lines):
        if line.strip() != "```":
            continue
        if start is None:
            start = idx
        else:
            block = lines[start + 1:idx]
            if any(
                (parts := item.split(None, 1))
                and len(parts) == 2
                and re.fullmatch(r"[0-9a-f]{64}", parts[0])
                and parts[1].strip() in production_paths
                for item in block
            ):
                ranges.append((start, idx))
            start = None
    if not ranges:
        raise SystemExit(f"provenance hash block not found: {PROVENANCE}")
    block = ["```"]
    for rel in _production_relpaths():
        block.append(f"{hashes[rel]}  {rel}")
    block.append("```")
    for start, end in reversed(ranges):
        lines[start:end + 1] = block
    PROVENANCE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _check_source_hashes() -> list[str]:
    """Compare the committed source copies against the provenance record."""
    recorded = _provenance_hashes()
    problems: list[str] = []
    for rel in _production_relpaths():
        path = IMPL_SRC / rel
        if not path.is_file():
            problems.append(f"missing source copy: {rel}")
            continue
        actual = hashlib.sha256(path.read_bytes()).hexdigest()
        expected = recorded.get(rel)
        if expected is None:
            problems.append(f"no provenance hash recorded for {rel}")
        elif actual != expected:
            problems.append(
                f"DRIFT: {rel} differs from the recorded provenance hash "
                f"(refresh via scripts/sync_codegen_fixtures.py pull)"
            )
    return problems


def _sha(path: Path) -> str:
    if not path.exists():
        return "<missing>"
    return hashlib.sha256(path.read_bytes()).hexdigest()[:16]


def _same(a: Path, b: Path) -> bool:
    if not a.exists() or not b.exists():
        return False
    return a.read_bytes() == b.read_bytes()


def _allowed_endpoint_classifications(path: Path) -> frozenset[str]:
    """Return the explicit endpoint-state policy for one fixture family."""
    return _ENDPOINT_POLICY.get(
        path.name,
        frozenset({"resolves in-document"}),
    )


def _validate_portable_json(path: Path) -> list[str]:
    """Validate a JSON graph without modifying it.

    This deliberately shares the strict canonical decoder with runtime graph
    deserialization.  It catches stale generated artifacts before a fixture
    refresh can make them appear authoritative.
    """
    if not path.is_file() or path.suffix.lower() != ".json":
        return []
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:
        return [f"{path}: cannot read JSON: {exc}"]
    if not isinstance(data, list):
        return []

    problems: list[str] = []
    nodes: dict[str, str] = {}
    edge_records: list[dict] = []

    def walk(entry: object) -> None:
        if not isinstance(entry, dict):
            problems.append(f"{path}: graph entry is not an object")
            return
        bad = _FORBIDDEN_NODE_FIELDS & set(entry)
        if bad:
            problems.append(f"{path}: node has forbidden fields {sorted(bad)}")
        key = entry.get("canonical_key")
        if not isinstance(key, str) or not key:
            problems.append(f"{path}: node is missing canonical_key")
        else:
            try:
                CanonicalIdentity.from_key(key)
            except ValueError as exc:
                problems.append(f"{path}: invalid canonical_key {key!r}: {exc}")
            import json as _json
            fingerprint = _json.dumps(
                {k: v for k, v in entry.items()
                 if k not in _FORBIDDEN_NODE_FIELDS | {"canonical_key"}},
                sort_keys=True,
            )
            previous = nodes.get(key)
            if previous is not None and previous != fingerprint:
                problems.append(
                    f"{path}: distinct nodes share canonical_key {key!r}"
                )
            nodes.setdefault(key, fingerprint)
        source_scope = entry.get("source") or "<unknown>"
        for edge in entry.get("edges", []):
            if not isinstance(edge, dict):
                problems.append(f"{path}: edge is not an object")
                continue
            bad_edge = _FORBIDDEN_EDGE_FIELDS & set(edge)
            if bad_edge:
                problems.append(f"{path}: edge has forbidden fields {sorted(bad_edge)}")
            relation_type = edge.get("relation_type")
            target_type = edge.get("target_type")
            if not isinstance(relation_type, str) or not relation_type:
                # Keep recording the edge so the grouped report identifies
                # it as malformed rather than silently dropping it.
                relation_valid = False
            else:
                relation_valid = True
            if not isinstance(target_type, str) or not target_type:
                target_type_valid = False
            else:
                target_type_valid = True
            if not isinstance(relation_type, str) or not relation_type:
                problems.append(f"{path}: edge is missing relation_type")
            if not isinstance(target_type, str) or not target_type:
                problems.append(f"{path}: edge is missing target_type")
            target = edge.get("target_key")
            target_ref = edge.get("target_ref")
            valid_target = False
            valid_shape = relation_valid and target_type_valid
            strict_complete = path.name == "codegraph_as_built.json"
            if target_ref and (strict_complete or path.name == "design_layergraph.json"):
                valid_shape = False
                if isinstance(target_ref, str) and re.fullmatch(
                    r"[0-9a-f]{40}", target_ref
                ):
                    problems.append(
                        f"{path}: UID-shaped target_ref is forbidden in a "
                        "complete as-built fixture"
                    )
                else:
                    problems.append(
                        f"{path}: target_ref is forbidden in a complete "
                        "as-built fixture"
                    )
            if strict_complete and edge.get("unresolved") is True:
                valid_shape = False
                problems.append(
                    f"{path}: unresolved endpoints are forbidden in the "
                    "complete as-built fixture"
                )
            if strict_complete and "diagnostic" in edge:
                valid_shape = False
                problems.append(
                    f"{path}: migration diagnostics are forbidden in the "
                    "complete as-built fixture"
                )
            if target is not None:
                if not isinstance(target, str) or not target:
                    valid_shape = False
                    problems.append(f"{path}: edge target_key must be a non-empty string")
                else:
                    valid_target = True
                    if target_ref:
                        valid_shape = False
                        problems.append(
                            f"{path}: edge cannot carry both target_key and target_ref"
                        )
                    try:
                        CanonicalIdentity.from_key(target)
                    except ValueError as exc:
                        valid_target = False
                        valid_shape = False
                        problems.append(f"{path}: invalid edge target_key {target!r}: {exc}")
            elif target_ref:
                if not isinstance(target_ref, str):
                    valid_shape = False
                    problems.append(f"{path}: edge target_ref must be a non-empty string")
                if edge.get("external") is True:
                    valid_shape = False
                    problems.append(
                        f"{path}: unresolved target_ref edge cannot be external"
                    )
                if edge.get("unresolved") is not True:
                    valid_shape = False
                    problems.append(
                        f"{path}: target_ref edge must declare unresolved: true"
                    )
                if not isinstance(edge.get("diagnostic"), str) or not edge[
                    "diagnostic"
                ].strip():
                    valid_shape = False
                    problems.append(
                        f"{path}: unresolved target_ref edge needs a diagnostic"
                    )
            else:
                valid_shape = False
                problems.append(f"{path}: edge has no target_key or explicit target_ref")

            if "external" in edge and not isinstance(edge["external"], bool):
                valid_shape = False
                problems.append(f"{path}: edge external must be boolean")
            if "unresolved" in edge and not isinstance(edge["unresolved"], bool):
                valid_shape = False
                problems.append(f"{path}: edge unresolved must be boolean")
            if edge.get("unresolved") is True and target is not None:
                valid_shape = False
                problems.append(
                    f"{path}: unresolved edge cannot carry target_key"
                )
            if edge.get("external") is True and not valid_target:
                valid_shape = False
                problems.append(
                    f"{path}: external requires a valid canonical target_key"
                )
            edge_records.append({
                "source_scope": source_scope,
                "relation_type": relation_type or "<missing>",
                "target_type": target_type or "<missing>",
                "target": target,
                "target_ref": target_ref,
                "valid_target": valid_target,
                "valid_shape": valid_shape,
                "edge": edge,
            })
        for child in entry.get("composes", []):
            walk(child)

    for entry in data:
        walk(entry)

    classifications: Counter[tuple[str, str, str, str, str]] = Counter()
    endpoint_sets: dict[tuple[str, str, str, str, str], set[str]] = {}
    allowed_classifications = _allowed_endpoint_classifications(path)
    for record in edge_records:
        target = record["target"]
        edge = record["edge"]
        if not record["valid_shape"]:
            classification = "malformed/ambiguous"
        elif target and record["valid_target"] and target in nodes:
            if edge.get("external") is True:
                classification = "malformed/ambiguous"
                problems.append(
                    f"{path}: in-document endpoint is also external: {target}"
                )
            elif edge.get("unresolved") is True:
                classification = "malformed/ambiguous"
                problems.append(
                    f"{path}: in-document endpoint is also unresolved: {target}"
                )
            else:
                classification = "resolves in-document"
        elif target and record["valid_target"] and edge.get("external") is True:
            classification = "canonical external target"
        elif record["target_ref"]:
            classification = "genuinely missing"
        elif target:
            classification = "malformed/ambiguous"
            problems.append(
                f"{path}: endpoint does not resolve and is not classified external: {target}"
            )
        else:
            classification = "malformed/ambiguous"
        if classification not in allowed_classifications:
            problems.append(
                f"{path}: endpoint classification {classification!r} is not "
                f"allowed for fixture family {path.name!r}"
            )
        group = (
            path.name,
            record["relation_type"],
            record["source_scope"],
            record["target_type"],
        )
        key = (*group, classification)
        classifications[key] += 1
        endpoint_sets.setdefault(key, set()).add(
            target or record["target_ref"] or "<missing>"
        )

    if classifications:
        print(f"portable endpoint inventory: {path.name}")
        for key in sorted(classifications):
            count = classifications[key]
            unique = len(endpoint_sets[key])
            _, relation, source, target_type, classification = key
            print(
                f"  {classification}: findings={count} unique_endpoints={unique} "
                f"relation={relation} source={source} target_type={target_type}"
            )
    return problems


def _sync_impl_source() -> None:
    """Sync the committed source copies under ``cpp_sqlite_impl_src`` with
    the sister repo's fixture directory — the project's source files
    (``.hpp``/``.cpp`` under ``cpp_sqlite/``) plus the ``.doxygen-index.toml``
    the round-trip index step needs, mirrored under their
    ``tests/fixtures/cpp-sqlite/...`` relative paths.  Build artifacts,
    dotfiles, CMakeLists and test harnesses are not part of the
    byte-for-byte contract."""
    for rel in sorted(SISTER_FIXTURE_SRC.rglob("*")):
        if not rel.is_file():
            continue
        if rel.suffix.lower() not in (".hpp", ".cpp"):
            continue
        if "cpp_sqlite" not in rel.parts:
            continue
        dst = IMPL_SRC / "tests/fixtures/cpp-sqlite" / rel.relative_to(SISTER_FIXTURE_SRC)
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(rel, dst)
    fixture_root = IMPL_SRC / "tests/fixtures/cpp-sqlite"
    for metadata_name in (".doxygen-index.toml", "conanfile.py", "conandata.yml"):
        metadata = SISTER_FIXTURE_SRC / metadata_name
        if metadata.is_file():
            dst = fixture_root / metadata_name
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(metadata, dst)


def check() -> int:
    failures = 0
    print(f"pipeline copy : {PIPELINE_COPY} {_sha(PIPELINE_COPY)}")
    print(f"golden        : {GOLDEN} {_sha(GOLDEN)}")
    print(f"sister repo   : {SISTER_CANONICAL} {_sha(SISTER_CANONICAL)}")
    print(f"one-hop       : {ONE_HOP} {_sha(ONE_HOP)}")
    print(f"impl export   : {IMPL} {_sha(IMPL)}")
    print(f"complete      : {COMPLETE_GRAPH} {_sha(COMPLETE_GRAPH)}")
    if SISTER.exists():
        if not _same(PIPELINE_COPY, SISTER_CANONICAL):
            print("DRIFT: pipeline copy != sister repo (generator output not pushed)")
            failures += 1
        if not _same(GOLDEN, SISTER_CANONICAL):
            print("DRIFT: golden != sister repo (run pull)")
            failures += 1
        if not _same(ONE_HOP, SISTER_ONE_HOP):
            print("DRIFT: one-hop != sister repo (run pull)")
            failures += 1
        if not _same(IMPL, SISTER_IMPL):
            print("DRIFT: impl export != sister repo (run pull)")
            failures += 1
    else:
        print(f"ERROR: sister repo not at {SISTER} — cross-repo checks cannot be performed")
        failures += 1
    if not GOLDEN.exists():
        print("DRIFT: golden missing")
        failures += 1
    if not ONE_HOP.exists():
        print("DRIFT: one-hop missing")
        failures += 1
    if not IMPL.exists():
        print("DRIFT: impl export missing")
        failures += 1
    if not IMPL_SRC.exists():
        print("DRIFT: impl source copies missing")
        failures += 1
    source_problems = _check_source_hashes()
    for problem in source_problems:
        print(problem)
        failures += 1
    if not source_problems:
        print("source copies: provenance hashes match")
    artifacts = [GOLDEN, ONE_HOP, IMPL, COMPLETE_GRAPH]
    if SISTER.exists():
        artifacts.extend((SISTER_CANONICAL, SISTER_ONE_HOP, SISTER_IMPL))
    for artifact in artifacts:
        for problem in _validate_portable_json(artifact):
            print(problem)
            failures += 1
    print("OK" if not failures else f"{failures} drift(s)")
    return 1 if failures else 0


def push() -> int:
    if not PIPELINE_COPY.exists():
        print(f"generator output not found: {PIPELINE_COPY}")
        print("run tests/pipelines/test_design_migration_manager.py first")
        return 1
    producer_problems = _validate_portable_json(PIPELINE_COPY)
    if producer_problems:
        for problem in producer_problems:
            print(problem)
        print("producer output rejected; no fixture copies were updated")
        return 1
    sister_available = SISTER.exists()
    if sister_available:
        shutil.copy2(PIPELINE_COPY, SISTER_CANONICAL)
        print(f"pushed → {SISTER_CANONICAL}")
    else:
        print(f"note: sister repo not at {SISTER} — skipped cross-repo copy")
    shutil.copy2(PIPELINE_COPY, GOLDEN)
    print(f"pushed → {GOLDEN}")
    if SISTER_IMPL.exists():
        shutil.copy2(SISTER_IMPL, IMPL)
        print(f"pushed → {IMPL}")
    if SISTER_FIXTURE_SRC.exists():
        _sync_impl_source()
        print(f"synced → {IMPL_SRC}")
    # A local push is useful in a single-repository sandbox; the authoritative
    # ``check`` command remains strict and reports a missing sister repository.
    return check() if sister_available else 0


def pull() -> int:
    """Adopt the sister repo as canonical: copy it over the golden."""
    if not SISTER_CANONICAL.exists():
        print(f"sister repo canonical not found: {SISTER_CANONICAL}")
        return 1
    shutil.copy2(SISTER_CANONICAL, GOLDEN)
    print(f"pulled → {GOLDEN}")
    if not _same(PIPELINE_COPY, SISTER_CANONICAL):
        print(
            "note: pipeline generator output differs from the adopted "
            "canonical — run push after the next generator run"
        )
    if SISTER_ONE_HOP.exists():
        shutil.copy2(SISTER_ONE_HOP, ONE_HOP)
        print(f"pulled → {ONE_HOP}")
    if SISTER_IMPL.exists():
        shutil.copy2(SISTER_IMPL, IMPL)
        print(f"pulled → {IMPL}")
    if SISTER_FIXTURE_SRC.exists():
        _sync_impl_source()
        print(f"synced → {IMPL_SRC}")
    # Re-record the golden source-copy hashes after the refresh so ``check``
    # verifies against the newly adopted bytes (explicit refresh only).
    hashes = {
        rel: hashlib.sha256((IMPL_SRC / rel).read_bytes()).hexdigest()
        for rel in _production_relpaths()
        if (IMPL_SRC / rel).is_file()
    }
    _write_provenance_hashes(hashes)
    print(f"provenance re-recorded → {PROVENANCE}")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Run the requested sync action."""
    if argv is None:
        argv = sys.argv[1:]
    if len(argv) != 1 or argv[0] not in ("push", "pull", "check"):
        print(__doc__)
        return 2
    return {"push": push, "pull": pull, "check": check}[argv[0]]()


if __name__ == "__main__":
    sys.exit(main())
