#!/usr/bin/env python3
"""Sync the codegen golden design fixture between repos (R1).

The canonical design LayerGraph lives in the sister repo
``doxygen-dependency-parser/tests/data/design_layergraph.json``.  The
codegraph repo keeps a reviewed golden at
``tests/codegen/golden/design_layergraph.json`` plus the fresh
generator output at ``tests/pipelines/unit_test_data/design_layergraph.json``
(written by ``tests/pipelines/test_design_migration_manager.py``).

Actions
-------
push   generated pipeline copy → sister repo  → golden (refresh all)
pull   sister repo → golden (sister regenerated; pull the new canonical)
check  byte-compare all three; fail on drift

Usage::

    python scripts/sync_codegen_fixtures.py check
    python scripts/sync_codegen_fixtures.py push
"""

from __future__ import annotations

import hashlib
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
# The actual workspace repository.  Keep this spelling explicit: macOS may
# resolve a differently-cased path while tooling and provenance records do not.
SISTER = ROOT.parent / "Doxygen-Dependency-Parser"

PIPELINE_COPY = ROOT / "tests/pipelines/unit_test_data/design_layergraph.json"
GOLDEN = ROOT / "tests/codegen/golden/design_layergraph.json"
SISTER_CANONICAL = SISTER / "tests/data/design_layergraph.json"

#: The cpp-sqlite one-hop as-built graph — generated by the sister repo's
#: ``tests/cpp_sqlite_integration/`` suite (``LayerGraph.from_backend`` +
#: ``serialize(fields="all")``).  Here it is a pinned input for
#: ``tests/codegen/test_cpp_sqlite_one_hop.py``; the sister repo is the
#: canonical source (pull to adopt a fresh export).
ONE_HOP = ROOT / "tests/unit_test_data/cpp_sqlite_one_hop.json"
SISTER_ONE_HOP = SISTER / "tests/unit_test_data/cpp_sqlite_one_hop.json"

#: The implementation-bearing export (``serialize(fields="all",
#: export_implementation=True)``): MethodNodes carry their implementation
#: ``body``/``body_file`` and INCLUDES edges carry the include spelling —
#: the semantic-reconstruction input for
#: ``tests/codegen/test_cpp_sqlite_one_hop.py::TestImplementationExport``.
IMPL = ROOT / "tests/unit_test_data/cpp_sqlite_one_hop_impl.json"
SISTER_IMPL = SISTER / "tests/unit_test_data/cpp_sqlite_one_hop_impl.json"

#: The original cpp-sqlite sources the byte-for-byte suite regenerates
#: and compares against (committed copies of
#: ``sister/tests/fixtures/cpp-sqlite/``).
IMPL_SRC = ROOT / "tests/unit_test_data/cpp_sqlite_impl_src"
SISTER_FIXTURE_SRC = SISTER / "tests/fixtures/cpp-sqlite"


def _sha(path: Path) -> str:
    if not path.exists():
        return "<missing>"
    return hashlib.sha256(path.read_bytes()).hexdigest()[:16]


def _same(a: Path, b: Path) -> bool:
    if not a.exists() or not b.exists():
        return False
    return a.read_bytes() == b.read_bytes()


def _sync_impl_source() -> None:
    """Sync the committed source copies under ``cpp_sqlite_impl_src`` with
    the sister repo's fixture directory — the project's source files
    (``.hpp``/``.cpp`` under ``cpp_sqlite/``) plus the ``.doxygen-index.toml``
    the round-trip index step needs, mirrored under their
    ``tests/fixtures/cpp-sqlite/...`` relative paths.  Build artifacts,
    dotfiles, CMakeLists and test harnesses are not part of the
    byte-for-byte contract."""
    for rel in sorted(SISTER_FIXTURE_SRC.rglob("*")):
        if not rel.is_file():
            continue
        if rel.suffix.lower() not in (".hpp", ".cpp"):
            continue
        if "cpp_sqlite" not in rel.parts:
            continue
        dst = IMPL_SRC / "tests/fixtures/cpp-sqlite" / rel.relative_to(SISTER_FIXTURE_SRC)
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(rel, dst)
    config = SISTER_FIXTURE_SRC / ".doxygen-index.toml"
    if config.is_file():
        dst = IMPL_SRC / "tests/fixtures/cpp-sqlite" / ".doxygen-index.toml"
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(config, dst)


def check() -> int:
    failures = 0
    print(f"pipeline copy : {PIPELINE_COPY} {_sha(PIPELINE_COPY)}")
    print(f"golden        : {GOLDEN} {_sha(GOLDEN)}")
    print(f"sister repo   : {SISTER_CANONICAL} {_sha(SISTER_CANONICAL)}")
    print(f"one-hop       : {ONE_HOP} {_sha(ONE_HOP)}")
    print(f"impl export   : {IMPL} {_sha(IMPL)}")
    if SISTER.exists():
        if not _same(PIPELINE_COPY, SISTER_CANONICAL):
            print("DRIFT: pipeline copy != sister repo (generator output not pushed)")
            failures += 1
        if not _same(GOLDEN, SISTER_CANONICAL):
            print("DRIFT: golden != sister repo (run pull)")
            failures += 1
        if not _same(ONE_HOP, SISTER_ONE_HOP):
            print("DRIFT: one-hop != sister repo (run pull)")
            failures += 1
        if not _same(IMPL, SISTER_IMPL):
            print("DRIFT: impl export != sister repo (run pull)")
            failures += 1
    else:
        print(f"note: sister repo not at {SISTER} — skipping cross-repo checks")
    if not GOLDEN.exists():
        print("DRIFT: golden missing")
        failures += 1
    if not ONE_HOP.exists():
        print("DRIFT: one-hop missing")
        failures += 1
    if not IMPL.exists():
        print("DRIFT: impl export missing")
        failures += 1
    if not IMPL_SRC.exists():
        print("DRIFT: impl source copies missing")
        failures += 1
    print("OK" if not failures else f"{failures} drift(s)")
    return 1 if failures else 0


def push() -> int:
    if not PIPELINE_COPY.exists():
        print(f"generator output not found: {PIPELINE_COPY}")
        print("run tests/pipelines/test_design_migration_manager.py first")
        return 1
    if SISTER.exists():
        shutil.copy2(PIPELINE_COPY, SISTER_CANONICAL)
        print(f"pushed → {SISTER_CANONICAL}")
    else:
        print(f"note: sister repo not at {SISTER} — skipped cross-repo copy")
    shutil.copy2(PIPELINE_COPY, GOLDEN)
    print(f"pushed → {GOLDEN}")
    if SISTER_IMPL.exists():
        shutil.copy2(SISTER_IMPL, IMPL)
        print(f"pushed → {IMPL}")
    if SISTER_FIXTURE_SRC.exists():
        _sync_impl_source()
        print(f"synced → {IMPL_SRC}")
    return check()


def pull() -> int:
    """Adopt the sister repo as canonical: copy it over the golden."""
    if not SISTER_CANONICAL.exists():
        print(f"sister repo canonical not found: {SISTER_CANONICAL}")
        return 1
    shutil.copy2(SISTER_CANONICAL, GOLDEN)
    print(f"pulled → {GOLDEN}")
    if not _same(PIPELINE_COPY, SISTER_CANONICAL):
        print(
            "note: pipeline generator output differs from the adopted "
            "canonical — run push after the next generator run"
        )
    if SISTER_ONE_HOP.exists():
        shutil.copy2(SISTER_ONE_HOP, ONE_HOP)
        print(f"pulled → {ONE_HOP}")
    if SISTER_IMPL.exists():
        shutil.copy2(SISTER_IMPL, IMPL)
        print(f"pulled → {IMPL}")
    if SISTER_FIXTURE_SRC.exists():
        _sync_impl_source()
        print(f"synced → {IMPL_SRC}")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Run the requested sync action."""
    if argv is None:
        argv = sys.argv[1:]
    if len(argv) != 1 or argv[0] not in ("push", "pull", "check"):
        print(__doc__)
        return 2
    return {"push": push, "pull": pull, "check": check}[argv[0]]()


if __name__ == "__main__":
    sys.exit(main())
