#!/usr/bin/env python3
"""Sync the codegen golden design fixture between repos (R1).

The canonical design LayerGraph lives in the sister repo
``doxygen-dependency-parser/tests/data/design_layergraph.json``.  The
codegraph repo keeps a reviewed golden at
``tests/codegen/golden/design_layergraph.json`` plus the fresh
generator output at ``tests/pipelines/unit_test_data/design_layergraph.json``
(written by ``tests/pipelines/test_design_migration_manager.py``).

Actions
-------
push   generated pipeline copy → sister repo  → golden (refresh all)
pull   sister repo → golden (sister regenerated; pull the new canonical)
check  byte-compare all three; fail on drift

Usage::

    python scripts/sync_codegen_fixtures.py check
    python scripts/sync_codegen_fixtures.py push
"""

from __future__ import annotations

import hashlib
import re
import shutil
import sys
from pathlib import Path

from codegraph.identity import CanonicalIdentity

ROOT = Path(__file__).resolve().parent.parent
# The actual workspace repository.  Keep this spelling explicit: macOS may
# resolve a differently-cased path while tooling and provenance records do not.
SISTER = ROOT.parent / "Doxygen-Dependency-Parser"

PIPELINE_COPY = ROOT / "tests/pipelines/unit_test_data/design_layergraph.json"
GOLDEN = ROOT / "tests/codegen/golden/design_layergraph.json"
SISTER_CANONICAL = SISTER / "tests/data/design_layergraph.json"

#: The cpp-sqlite one-hop as-built graph — generated by the sister repo's
#: ``tests/cpp_sqlite_integration/`` suite (``LayerGraph.from_backend`` +
#: ``serialize(fields="all")``).  Here it is a pinned input for
#: ``tests/codegen/test_cpp_sqlite_one_hop.py``; the sister repo is the
#: canonical source (pull to adopt a fresh export).
ONE_HOP = ROOT / "tests/unit_test_data/cpp_sqlite_one_hop.json"
SISTER_ONE_HOP = SISTER / "tests/unit_test_data/cpp_sqlite_one_hop.json"

#: The implementation-bearing export (``serialize(fields="all",
#: export_implementation=True)``): MethodNodes carry their implementation
#: ``body``/``body_file`` and INCLUDES edges carry the include spelling —
#: the semantic-reconstruction input for
#: ``tests/codegen/test_cpp_sqlite_one_hop.py::TestImplementationExport``.
IMPL = ROOT / "tests/unit_test_data/cpp_sqlite_one_hop_impl.json"
SISTER_IMPL = SISTER / "tests/unit_test_data/cpp_sqlite_one_hop_impl.json"

#: The original cpp-sqlite sources the byte-for-byte suite regenerates
#: and compares against (committed copies of
#: ``sister/tests/fixtures/cpp-sqlite/``).
IMPL_SRC = ROOT / "tests/unit_test_data/cpp_sqlite_impl_src"
SISTER_FIXTURE_SRC = SISTER / "tests/fixtures/cpp-sqlite"

#: The 14-file production manifest + the provenance record pinning the
#: golden source-copy hashes (``check`` verifies, ``pull`` re-records).
MANIFEST = ROOT / "tests/codegen/cpp_sqlite_roundtrip_manifest.txt"
PROVENANCE = ROOT / "tests/codegen/cpp_sqlite_roundtrip_provenance.md"

#: The two test files stay outside source byte-fidelity (constraint 3).
TEST_FILES = frozenset({
    "tests/fixtures/cpp-sqlite/cpp_sqlite/test/testDatabase.cpp",
    "tests/fixtures/cpp-sqlite/cpp_sqlite/test/testDatabase.hpp",
})

_FORBIDDEN_NODE_FIELDS = frozenset({
    "uid", "refid", "compound_refid", "member_refid", "parent_refid",
    "child_refid", "from_refid", "to_refid",
})
_FORBIDDEN_EDGE_FIELDS = frozenset({
    "uid", "target_uid", "refid", "from_refid", "to_refid",
})


def _production_relpaths() -> list[str]:
    """The 14 production paths from the manifest (relative to IMPL_SRC)."""
    return [
        line.strip()
        for line in MANIFEST.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]


def _provenance_hashes() -> dict[str, str]:
    """Parse the golden source-copy hashes recorded in the provenance file."""
    if not PROVENANCE.is_file():
        return {}
    production_paths = set(_production_relpaths())
    hashes: dict[str, str] = {}
    in_block = False
    for line in PROVENANCE.read_text(encoding="utf-8").splitlines():
        if line.strip() == "```":
            in_block = not in_block
            continue
        if not in_block:
            continue
        parts = line.split(None, 1)
        if (
            len(parts) == 2
            and re.fullmatch(r"[0-9a-f]{64}", parts[0])
            and parts[1].strip() in production_paths
        ):
            hashes[parts[1].strip()] = parts[0]
    return hashes


def _write_provenance_hashes(hashes: dict[str, str]) -> None:
    """Rewrite every source-hash block (``pull`` only).

    A provenance document may contain more than one hash block.  Update only
    fenced blocks containing strict hash/path records so path-only manifest
    blocks remain documentation rather than being converted into hashes.
    """
    lines = PROVENANCE.read_text(encoding="utf-8").splitlines()
    production_paths = set(_production_relpaths())
    ranges: list[tuple[int, int]] = []
    start: int | None = None
    for idx, line in enumerate(lines):
        if line.strip() != "```":
            continue
        if start is None:
            start = idx
        else:
            block = lines[start + 1:idx]
            if any(
                (parts := item.split(None, 1))
                and len(parts) == 2
                and re.fullmatch(r"[0-9a-f]{64}", parts[0])
                and parts[1].strip() in production_paths
                for item in block
            ):
                ranges.append((start, idx))
            start = None
    if not ranges:
        raise SystemExit(f"provenance hash block not found: {PROVENANCE}")
    block = ["```"]
    for rel in _production_relpaths():
        block.append(f"{hashes[rel]}  {rel}")
    block.append("```")
    for start, end in reversed(ranges):
        lines[start:end + 1] = block
    PROVENANCE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _check_source_hashes() -> list[str]:
    """Compare the committed source copies against the provenance record."""
    recorded = _provenance_hashes()
    problems: list[str] = []
    for rel in _production_relpaths():
        path = IMPL_SRC / rel
        if not path.is_file():
            problems.append(f"missing source copy: {rel}")
            continue
        actual = hashlib.sha256(path.read_bytes()).hexdigest()
        expected = recorded.get(rel)
        if expected is None:
            problems.append(f"no provenance hash recorded for {rel}")
        elif actual != expected:
            problems.append(
                f"DRIFT: {rel} differs from the recorded provenance hash "
                f"(refresh via scripts/sync_codegen_fixtures.py pull)"
            )
    return problems


def _sha(path: Path) -> str:
    if not path.exists():
        return "<missing>"
    return hashlib.sha256(path.read_bytes()).hexdigest()[:16]


def _same(a: Path, b: Path) -> bool:
    if not a.exists() or not b.exists():
        return False
    return a.read_bytes() == b.read_bytes()


def _validate_portable_json(path: Path) -> list[str]:
    """Validate a JSON graph without modifying it.

    This deliberately shares the strict canonical decoder with runtime graph
    deserialization.  It catches stale generated artifacts before a fixture
    refresh can make them appear authoritative.
    """
    if not path.is_file() or path.suffix.lower() != ".json":
        return []
    try:
        import json
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:
        return [f"{path}: cannot read JSON: {exc}"]
    if not isinstance(data, list):
        return []

    problems: list[str] = []
    nodes: dict[str, str] = {}
    entries: list[dict] = []

    def walk(entry: object) -> None:
        if not isinstance(entry, dict):
            problems.append(f"{path}: graph entry is not an object")
            return
        entries.append(entry)
        bad = _FORBIDDEN_NODE_FIELDS & set(entry)
        if bad:
            problems.append(f"{path}: node has forbidden fields {sorted(bad)}")
        key = entry.get("canonical_key")
        if not isinstance(key, str) or not key:
            problems.append(f"{path}: node is missing canonical_key")
        else:
            try:
                CanonicalIdentity.from_key(key)
            except ValueError as exc:
                problems.append(f"{path}: invalid canonical_key {key!r}: {exc}")
            import json as _json
            fingerprint = _json.dumps(
                {k: v for k, v in entry.items()
                 if k not in _FORBIDDEN_NODE_FIELDS | {"canonical_key"}},
                sort_keys=True,
            )
            previous = nodes.get(key)
            if previous is not None and previous != fingerprint:
                problems.append(
                    f"{path}: distinct nodes share canonical_key {key!r}"
                )
            nodes.setdefault(key, fingerprint)
        for edge in entry.get("edges", []):
            if not isinstance(edge, dict):
                problems.append(f"{path}: edge is not an object")
                continue
            bad_edge = _FORBIDDEN_EDGE_FIELDS & set(edge)
            if bad_edge:
                problems.append(f"{path}: edge has forbidden fields {sorted(bad_edge)}")
            target = edge.get("target_key")
            if target:
                try:
                    CanonicalIdentity.from_key(target)
                except ValueError as exc:
                    problems.append(f"{path}: invalid edge target_key {target!r}: {exc}")
            elif not edge.get("target_ref"):
                problems.append(f"{path}: edge has no target_key or explicit target_ref")
        for child in entry.get("composes", []):
            walk(child)

    for entry in data:
        walk(entry)
    for entry in entries:
        for edge in entry.get("edges", []):
            target = edge.get("target_key")
            if target and target not in nodes and not (
                edge.get("target_ref") or edge.get("external") is True
            ):
                problems.append(
                    f"{path}: in-document endpoint does not resolve and is not "
                    f"classified external: {target}"
                )
    return problems


def _sync_impl_source() -> None:
    """Sync the committed source copies under ``cpp_sqlite_impl_src`` with
    the sister repo's fixture directory — the project's source files
    (``.hpp``/``.cpp`` under ``cpp_sqlite/``) plus the ``.doxygen-index.toml``
    the round-trip index step needs, mirrored under their
    ``tests/fixtures/cpp-sqlite/...`` relative paths.  Build artifacts,
    dotfiles, CMakeLists and test harnesses are not part of the
    byte-for-byte contract."""
    for rel in sorted(SISTER_FIXTURE_SRC.rglob("*")):
        if not rel.is_file():
            continue
        if rel.suffix.lower() not in (".hpp", ".cpp"):
            continue
        if "cpp_sqlite" not in rel.parts:
            continue
        dst = IMPL_SRC / "tests/fixtures/cpp-sqlite" / rel.relative_to(SISTER_FIXTURE_SRC)
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(rel, dst)
    fixture_root = IMPL_SRC / "tests/fixtures/cpp-sqlite"
    for metadata_name in (".doxygen-index.toml", "conanfile.py", "conandata.yml"):
        metadata = SISTER_FIXTURE_SRC / metadata_name
        if metadata.is_file():
            dst = fixture_root / metadata_name
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(metadata, dst)


def check() -> int:
    failures = 0
    print(f"pipeline copy : {PIPELINE_COPY} {_sha(PIPELINE_COPY)}")
    print(f"golden        : {GOLDEN} {_sha(GOLDEN)}")
    print(f"sister repo   : {SISTER_CANONICAL} {_sha(SISTER_CANONICAL)}")
    print(f"one-hop       : {ONE_HOP} {_sha(ONE_HOP)}")
    print(f"impl export   : {IMPL} {_sha(IMPL)}")
    if SISTER.exists():
        if not _same(PIPELINE_COPY, SISTER_CANONICAL):
            print("DRIFT: pipeline copy != sister repo (generator output not pushed)")
            failures += 1
        if not _same(GOLDEN, SISTER_CANONICAL):
            print("DRIFT: golden != sister repo (run pull)")
            failures += 1
        if not _same(ONE_HOP, SISTER_ONE_HOP):
            print("DRIFT: one-hop != sister repo (run pull)")
            failures += 1
        if not _same(IMPL, SISTER_IMPL):
            print("DRIFT: impl export != sister repo (run pull)")
            failures += 1
    else:
        print(f"ERROR: sister repo not at {SISTER} — cross-repo checks cannot be performed")
        failures += 1
    if not GOLDEN.exists():
        print("DRIFT: golden missing")
        failures += 1
    if not ONE_HOP.exists():
        print("DRIFT: one-hop missing")
        failures += 1
    if not IMPL.exists():
        print("DRIFT: impl export missing")
        failures += 1
    if not IMPL_SRC.exists():
        print("DRIFT: impl source copies missing")
        failures += 1
    source_problems = _check_source_hashes()
    for problem in source_problems:
        print(problem)
        failures += 1
    if not source_problems:
        print("source copies: provenance hashes match")
    artifacts = [GOLDEN, ONE_HOP, IMPL]
    if SISTER.exists():
        artifacts.extend((SISTER_CANONICAL, SISTER_ONE_HOP, SISTER_IMPL))
    for artifact in artifacts:
        for problem in _validate_portable_json(artifact):
            print(problem)
            failures += 1
    print("OK" if not failures else f"{failures} drift(s)")
    return 1 if failures else 0


def push() -> int:
    if not PIPELINE_COPY.exists():
        print(f"generator output not found: {PIPELINE_COPY}")
        print("run tests/pipelines/test_design_migration_manager.py first")
        return 1
    sister_available = SISTER.exists()
    if sister_available:
        shutil.copy2(PIPELINE_COPY, SISTER_CANONICAL)
        print(f"pushed → {SISTER_CANONICAL}")
    else:
        print(f"note: sister repo not at {SISTER} — skipped cross-repo copy")
    shutil.copy2(PIPELINE_COPY, GOLDEN)
    print(f"pushed → {GOLDEN}")
    if SISTER_IMPL.exists():
        shutil.copy2(SISTER_IMPL, IMPL)
        print(f"pushed → {IMPL}")
    if SISTER_FIXTURE_SRC.exists():
        _sync_impl_source()
        print(f"synced → {IMPL_SRC}")
    # A local push is useful in a single-repository sandbox; the authoritative
    # ``check`` command remains strict and reports a missing sister repository.
    return check() if sister_available else 0


def pull() -> int:
    """Adopt the sister repo as canonical: copy it over the golden."""
    if not SISTER_CANONICAL.exists():
        print(f"sister repo canonical not found: {SISTER_CANONICAL}")
        return 1
    shutil.copy2(SISTER_CANONICAL, GOLDEN)
    print(f"pulled → {GOLDEN}")
    if not _same(PIPELINE_COPY, SISTER_CANONICAL):
        print(
            "note: pipeline generator output differs from the adopted "
            "canonical — run push after the next generator run"
        )
    if SISTER_ONE_HOP.exists():
        shutil.copy2(SISTER_ONE_HOP, ONE_HOP)
        print(f"pulled → {ONE_HOP}")
    if SISTER_IMPL.exists():
        shutil.copy2(SISTER_IMPL, IMPL)
        print(f"pulled → {IMPL}")
    if SISTER_FIXTURE_SRC.exists():
        _sync_impl_source()
        print(f"synced → {IMPL_SRC}")
    # Re-record the golden source-copy hashes after the refresh so ``check``
    # verifies against the newly adopted bytes (explicit refresh only).
    hashes = {
        rel: hashlib.sha256((IMPL_SRC / rel).read_bytes()).hexdigest()
        for rel in _production_relpaths()
        if (IMPL_SRC / rel).is_file()
    }
    _write_provenance_hashes(hashes)
    print(f"provenance re-recorded → {PROVENANCE}")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Run the requested sync action."""
    if argv is None:
        argv = sys.argv[1:]
    if len(argv) != 1 or argv[0] not in ("push", "pull", "check"):
        print(__doc__)
        return 2
    return {"push": push, "pull": pull, "check": check}[argv[0]]()


if __name__ == "__main__":
    sys.exit(main())
